import type {
  AssessmentItem,
  CognitiveDimension,
  Difficulty,
  InternalOption,
  PracticeItem,
  Stimulus,
} from "./types";

const textOption = (id: string, semanticSegments: string[], alt = semanticSegments.join("")): InternalOption => ({
  id,
  semanticSegments,
  alt,
});

const visualOption = (id: string, visualKey: string, alt: string): InternalOption => ({ id, visualKey, alt });

export const CATEGORY_LABELS: Record<CognitiveDimension, string> = {
  abstract: "抽象推理",
  spatial: "空間推理",
  quantitative: "數量推理",
  logic: "邏輯推理",
  workingMemory: "工作記憶",
  verbal: "語文概念",
  processingSpeed: "處理速度",
};

export const PRACTICE_ITEMS: AssessmentItem[] = [
  {
    id: "p01", category: "quantitative", difficulty: "easy",
    stem: "依照等差數列規律，下一個數字是？",
    semanticSegments: ["依照等差數列規律，", "下一個數字是？"],
    stimulus: {"kind": "sequence", "values": ["2", "4", "6", "？"]},
    options: [
      { id: "eight", alt: "8", semanticSegments: ["8"] },
      { id: "nine", alt: "9", semanticSegments: ["9"] },
      { id: "seven", alt: "7", semanticSegments: ["7"] },
      { id: "ten", alt: "10", semanticSegments: ["10"] }
    ],
    correctOptionId: "eight",
    distractorRationale: "9 反映未辨識固定加 2 的規則；7 反向減一；10 把最後一步誤作加四。",
    measurementTarget: "理解操作與最簡單等差規則。",
    internalExplanation: "每次增加 2，因此 6 之後是 8。",
    suggestedTimeSeconds: 8,
    provisionalA: 0.7,
    provisionalB: -2.0,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 2、4、6、問號。",
  },
  {
    id: "p02", category: "abstract", difficulty: "easy",
    stem: "圖形交替出現，下一個是？",
    semanticSegments: ["圖形交替出現，", "下一個是？"],
    stimulus: {"kind": "visual", "visualKey": "practice-alternation"},
    options: [
      { id: "square", alt: "空心正方形", visualKey: "option-square-outline" },
      { id: "triangle", alt: "空心三角形", visualKey: "option-triangle-outline" },
      { id: "filledCircle", alt: "實心圓形", visualKey: "option-circle-filled" },
      { id: "filledSquare", alt: "實心正方形", visualKey: "option-square-filled" }
    ],
    correctOptionId: "square",
    distractorRationale: "三角形不在交替規則中；實心圓與實心正方形額外改變了題目固定的空心屬性。",
    measurementTarget: "理解圖形選項與簡單交替規則。",
    internalExplanation: "圓形與正方形輪流出現，因此下一個是正方形。",
    suggestedTimeSeconds: 8,
    provisionalA: 0.7,
    provisionalB: -2.0,
    provisionalC: 0.25,
    accessibilityAlt: "空心圓、空心正方形、空心圓、問號。",
  },
];

export const ASSESSMENT_ITEMS: AssessmentItem[] = [
  {
    id: "q01", category: "abstract", difficulty: "easy",
    stem: "右下角應該放哪個圖形？",
    semanticSegments: ["右下角應該放", "哪個圖形？"],
    stimulus: {"kind": "visual", "visualKey": "matrix-fill"},
    options: [
      { id: "filled", alt: "實心正方形", visualKey: "option-square-filled" },
      { id: "outline", alt: "空心正方形", visualKey: "option-square-outline" },
      { id: "filledCircle", alt: "實心圓形", visualKey: "option-circle-filled" },
      { id: "outlineCircle", alt: "空心圓形", visualKey: "option-circle-outline" }
    ],
    correctOptionId: "filled",
    distractorRationale: "保留形狀卻忽略填色欄規則；兩個圓形選項忽略下排必須是正方形；空心圓另漏掉欄位填色。",
    measurementTarget: "辨識二乘二矩陣中的形狀與填色交叉規則。",
    internalExplanation: "每列左邊空心、右邊實心；每欄上方圓形、下方正方形，故右下角為實心正方形。",
    suggestedTimeSeconds: 12,
    provisionalA: 1.0,
    provisionalB: -1.35,
    provisionalC: 0.25,
    accessibilityAlt: "二乘二矩陣：上排空心圓、實心圓；下排空心正方形、缺格。",
  },
  {
    id: "q02", category: "verbal", difficulty: "easy",
    stem: "鳥和巢的關係，就像蜜蜂和什麼？",
    semanticSegments: ["鳥和巢的關係，", "就像蜜蜂和什麼？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "hive", alt: "蜂巢", semanticSegments: ["蜂巢"] },
      { id: "pollen", alt: "花粉", semanticSegments: ["花粉"] },
      { id: "flower", alt: "花朵", semanticSegments: ["花朵"] },
      { id: "honey", alt: "蜂蜜", semanticSegments: ["蜂蜜"] }
    ],
    correctOptionId: "hive",
    distractorRationale: "花粉與蜜蜂有關但不是居所；花朵是活動採蜜處；蜂蜜是產物，皆非動物與居所關係。",
    measurementTarget: "辨識具體概念間的同型居所關係。",
    internalExplanation: "巢是鳥的居所，蜂巢是蜜蜂的居所。",
    suggestedTimeSeconds: 10,
    provisionalA: 0.9,
    provisionalB: -1.25,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q03", category: "quantitative", difficulty: "easy",
    stem: "觀察數列的遞迴規律，下一個數字是？",
    semanticSegments: ["觀察數列的遞迴規律，", "下一個數字是？"],
    stimulus: {"kind": "sequence", "values": ["3", "6", "9", "12", "？"]},
    options: [
      { id: "fifteen", alt: "15", semanticSegments: ["15"] },
      { id: "fourteen", alt: "14", semanticSegments: ["14"] },
      { id: "eighteen", alt: "18", semanticSegments: ["18"] },
      { id: "thirteen", alt: "13", semanticSegments: ["13"] }
    ],
    correctOptionId: "fifteen",
    distractorRationale: "14 未維持固定加 3；18 誤作加 6；13 只加 1。",
    measurementTarget: "辨識單一等差數列。",
    internalExplanation: "相鄰兩數都增加 3，12 + 3 = 15。",
    suggestedTimeSeconds: 10,
    provisionalA: 0.95,
    provisionalB: -1.15,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 3、6、9、12、問號。",
  },
  {
    id: "q04", category: "spatial", difficulty: "easy",
    stem: "沿垂直線照鏡子後，哪個圖形正確？",
    semanticSegments: ["沿垂直線照鏡子後，", "哪個圖形正確？"],
    stimulus: {"kind": "visual", "visualKey": "mirror-l-easy"},
    options: [
      { id: "mirror", alt: "左右鏡像後的 L 形，圓點位於右上", visualKey: "mirror-l-correct" },
      { id: "rotate", alt: "旋轉後的 L 形，圓點位於左下", visualKey: "mirror-l-wrong" },
      { id: "unchanged", alt: "未翻轉的原 L 形，圓點位於左上", visualKey: "mirror-l-unchanged" },
      { id: "horizontal", alt: "上下翻面後的 L 形，圓點位於左下", visualKey: "mirror-l-horizontal" }
    ],
    correctOptionId: "mirror",
    distractorRationale: "旋轉選項把鏡像誤作旋轉；未翻轉選項漏做操作；上下翻面使用了水平鏡軸而非垂直軸。",
    measurementTarget: "區分垂直鏡像與旋轉或翻面。",
    internalExplanation: "垂直鏡面只翻轉左右：原本向右折的底邊改為向左折，原左上圓點移至右上。",
    suggestedTimeSeconds: 14,
    provisionalA: 1.05,
    provisionalB: -1.05,
    provisionalC: 0.25,
    accessibilityAlt: "垂直鏡線左側有一個 L 形，圓點位於左上。",
  },
  {
    id: "q05", category: "logic", difficulty: "easy",
    stem: "所有洛米都是藍色。這個物件是洛米。它必然是藍色嗎？",
    semanticSegments: ["所有洛米都是藍色。", "這個物件是洛米。", "它必然是藍色嗎？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "yes", alt: "必然是", semanticSegments: ["必然是"] },
      { id: "maybe", alt: "不一定", semanticSegments: ["不一定"] },
      { id: "no", alt: "必然不是", semanticSegments: ["必然不是"] },
      { id: "conflict", alt: "條件矛盾", semanticSegments: ["條件矛盾"] }
    ],
    correctOptionId: "yes",
    distractorRationale: "忽略全稱前提已涵蓋該個體；必然不是顛倒結論；條件矛盾誤認兩前提互斥。",
    measurementTarget: "單步全稱演繹推理。",
    internalExplanation: "個體屬於洛米集合，而所有洛米集合元素皆為藍色，因此必然為藍色。",
    suggestedTimeSeconds: 12,
    provisionalA: 0.9,
    provisionalB: -0.95,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形；洛米為中性代稱。",
  },
  {
    id: "q06", category: "processingSpeed", difficulty: "easy",
    stem: "方格中，哪兩格的符號完全相同？",
    semanticSegments: ["方格中，", "哪兩格的符號", "完全相同？"],
    stimulus: {"kind": "visual", "visualKey": "search-pair-easy"},
    options: [
      { id: "pairCorrect", alt: "第 2 列第 1 格與第 4 列第 3 格", semanticSegments: ["第 2 列第 1 格", "與第 4 列第 3 格"] },
      { id: "pairNear", alt: "第 1 列第 1 格與第 3 列第 1 格", semanticSegments: ["第 1 列第 1 格", "與第 3 列第 1 格"] },
      { id: "pairA", alt: "第 1 列第 2 格與第 3 列第 1 格", semanticSegments: ["第 1 列第 2 格", "與第 3 列第 1 格"] },
      { id: "pairB", alt: "第 2 列第 2 格與第 4 列第 4 格", semanticSegments: ["第 2 列第 2 格", "與第 4 列第 4 格"] }
    ],
    correctOptionId: "pairCorrect",
    distractorRationale: "其他組合皆只有缺口或圓點部分相似，並非完全相同。",
    measurementTarget: "簡單符號比對與視覺搜尋。",
    internalExplanation: "第二列第一格與第四列第三格符號皆為缺口朝下且無圓點，完全相同。",
    suggestedTimeSeconds: 10,
    provisionalA: 0.95,
    provisionalB: -0.8,
    provisionalC: 0.25,
    accessibilityAlt: "四乘四缺口圓形陣列，以列、格定位；其中只有一對完全相同。",
  },
  {
    id: "q07", category: "workingMemory", difficulty: "easy",
    stem: "把剛才的順序倒過來後，第 2 個項目是？",
    semanticSegments: ["把剛才的順序", "倒過來後，", "第 2 個項目是？"],
    stimulus: {"kind": "memory", "values": ["K", "4", "2", "M"], "durationMs": 7500},
    options: [
      { id: "two", alt: "2", semanticSegments: ["2"] },
      { id: "four", alt: "4", semanticSegments: ["4"] },
      { id: "m", alt: "M", semanticSegments: ["M"] },
      { id: "k", alt: "K", semanticSegments: ["K"] }
    ],
    correctOptionId: "two",
    distractorRationale: "4 是原順序第 2 項（未倒序）；M 是倒序後第 1 項；K 是倒序後末項。",
    measurementTarget: "四項保持與倒序定位。",
    internalExplanation: "原順序 K、4、2、M，倒序後為 M、2、4、K，第 2 個項目是 2。",
    suggestedTimeSeconds: 14,
    provisionalA: 1.05,
    provisionalB: -0.65,
    provisionalC: 0.25,
    accessibilityAlt: "先短暫顯示 K、4、2、M，接著隱藏。",
  },
  {
    id: "q08", category: "abstract", difficulty: "easy",
    stem: "依照每列的規則，缺少哪一格？",
    semanticSegments: ["依照每列的規則，", "缺少哪一格？"],
    stimulus: {"kind": "visual", "visualKey": "matrix-count"},
    options: [
      { id: "horizontal", alt: "橫向排列三個空心圓", visualKey: "dots-three-horizontal" },
      { id: "vertical", alt: "直向排列三個空心圓", visualKey: "dots-three-vertical" },
      { id: "twoHorizontal", alt: "橫向排列兩個空心圓", visualKey: "dots-two-horizontal" },
      { id: "fourHorizontal", alt: "橫向排列四個空心圓", visualKey: "dots-four-horizontal" }
    ],
    correctOptionId: "horizontal",
    distractorRationale: "直向改變了橫向排列的恆常性；兩個或四個圓分別停滯或過度增加。",
    measurementTarget: "視覺數量遞增與方向恆常性。",
    internalExplanation: "每列左右兩格圓數相同，第一列各 1、第二列各 2，第三列左格為 3，右格缺格亦為橫向 3 個圓。",
    suggestedTimeSeconds: 12,
    provisionalA: 1.0,
    provisionalB: -0.55,
    provisionalC: 0.25,
    accessibilityAlt: "三乘二矩陣：第一列各一圓、第二列各兩圓、第三列左格三圓、右格缺少。",
  },
  {
    id: "q09", category: "verbal", difficulty: "easy",
    stem: "輪胎之於汽車，就像螺旋槳之於什麼？",
    semanticSegments: ["輪胎之於汽車，", "就像螺旋槳之於什麼？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "airplane", alt: "飛機", semanticSegments: ["飛機"] },
      { id: "runway", alt: "跑道", semanticSegments: ["跑道"] },
      { id: "wing", alt: "機翼", semanticSegments: ["機翼"] },
      { id: "kite", alt: "風箏", semanticSegments: ["風箏"] }
    ],
    correctOptionId: "airplane",
    distractorRationale: "跑道是起降場所而非載具本體；機翼是升力部件而非提供推進的對應動力部件；風箏無螺旋槳。",
    measurementTarget: "功能部件與載具整體的對稱類比。",
    internalExplanation: "輪胎是汽車前進的驅動構件，螺旋槳是傳統推進式飛機前進的驅動構件。",
    suggestedTimeSeconds: 10,
    provisionalA: 0.9,
    provisionalB: -0.45,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q10", category: "spatial", difficulty: "easy",
    stem: "原本面向北方，先向右轉 90°，再向後轉 180°。現在面向哪個方向？",
    semanticSegments: ["原本面向北方，", "先向右轉 90°，", "再向後轉 180°。", "現在面向哪個方向？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "west", alt: "西方", semanticSegments: ["西方"] },
      { id: "east", alt: "東方", semanticSegments: ["東方"] },
      { id: "south", alt: "南方", semanticSegments: ["南方"] },
      { id: "northwest", alt: "西北方", semanticSegments: ["西北方"] }
    ],
    correctOptionId: "west",
    distractorRationale: "東方只完成右轉；南方誤把右轉當作向後轉；西北方非 90 度整數倍轉向。",
    measurementTarget: "方位心智旋轉與兩步方位更新。",
    internalExplanation: "面向北方，向右轉 90° 面向東方；再向後轉 180° 則面向西方。",
    suggestedTimeSeconds: 12,
    provisionalA: 0.95,
    provisionalB: -0.4,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q11", category: "quantitative", difficulty: "easy",
    stem: "依照數列規則，下一個數字是？",
    semanticSegments: ["依照數列規則，", "下一個數字是？"],
    stimulus: {"kind": "sequence", "values": ["28", "24", "20", "16", "？"]},
    options: [
      { id: "twelve", alt: "12", semanticSegments: ["12"] },
      { id: "ten", alt: "10", semanticSegments: ["10"] },
      { id: "fourteen", alt: "14", semanticSegments: ["14"] },
      { id: "eight", alt: "8", semanticSegments: ["8"] }
    ],
    correctOptionId: "twelve",
    distractorRationale: "10 誤作減 6；14 只減 2；8 誤多減了一次 4。",
    measurementTarget: "單一遞減等差數列。",
    internalExplanation: "相鄰兩數固定減少 4：16 - 4 = 12。",
    suggestedTimeSeconds: 10,
    provisionalA: 0.95,
    provisionalB: -0.35,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 28、24、20、16、問號。",
  },
  {
    id: "q12", category: "logic", difficulty: "easy",
    stem: "所有正方形都是四邊形。所有四邊形內角和都是 360°。由此可必然得出？",
    semanticSegments: ["所有正方形都是四邊形。", "所有四邊形內角和都是 360°。", "由此可必然得出？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "allSquare", alt: "所有正方形內角和都是 360°", semanticSegments: ["所有正方形內角和都是 360°"] },
      { id: "someSquare", alt: "只有部分正方形內角和是 360°", semanticSegments: ["只有部分正方形內角和是 360°"] },
      { id: "notSquare", alt: "並非所有四邊形都是正方形", semanticSegments: ["並非所有四邊形都是正方形"] },
      { id: "uncertain", alt: "無法確定正方形的內角和", semanticSegments: ["無法確定正方形的內角和"] }
    ],
    correctOptionId: "allSquare",
    distractorRationale: "只有部分違反全稱包含傳遞；並非所有四邊形雖屬實但非前兩句三段論直接結論；無法確定忽略邏輯必然性。",
    measurementTarget: "經典三段論（Barbara式）演繹推理。",
    internalExplanation: "正方形屬於四邊形，四邊形內角和皆為 360°，故所有正方形內角和必然皆為 360°。",
    suggestedTimeSeconds: 12,
    provisionalA: 0.95,
    provisionalB: -0.3,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q13", category: "workingMemory", difficulty: "easy",
    stem: "剛才出現的符號中，倒數第 2 個是？",
    semanticSegments: ["剛才出現的符號中，", "倒數第 2 個是？"],
    stimulus: {"kind": "memory", "values": ["★", "▲", "●", "◆", "■"], "durationMs": 8000},
    options: [
      { id: "diamond", alt: "◆", semanticSegments: ["◆"] },
      { id: "circle", alt: "●", semanticSegments: ["●"] },
      { id: "square", alt: "■", semanticSegments: ["■"] },
      { id: "triangle", alt: "▲", semanticSegments: ["▲"] }
    ],
    correctOptionId: "diamond",
    distractorRationale: "● 是正數第 3 個；■ 是最後一個（倒數第 1 個）；▲ 是正數第 2 個。",
    measurementTarget: "五項幾何符號短暫保持與逆向定位。",
    internalExplanation: "順序為 ★、▲、●、◆、■，最後一項為 ■，倒數第 2 個為 ◆。",
    suggestedTimeSeconds: 14,
    provisionalA: 1.0,
    provisionalB: -0.25,
    provisionalC: 0.25,
    accessibilityAlt: "先短暫顯示 ★、▲、●、◆、■，接著隱藏。",
  },
  {
    id: "q14", category: "abstract", difficulty: "easy",
    stem: "尺寸與形狀交替變化，下一個圖形是？",
    semanticSegments: ["尺寸與形狀交替變化，", "下一個圖形是？"],
    stimulus: {"kind": "sequence", "values": ["小正方形", "中正方形", "大正方形", "小圓形", "中圓形", "？"]},
    options: [
      { id: "largeCircle", alt: "大圓形", semanticSegments: ["大圓形"] },
      { id: "smallCircle", alt: "小圓形", semanticSegments: ["小圓形"] },
      { id: "largeSquare", alt: "大正方形", semanticSegments: ["大正方形"] },
      { id: "smallSquare", alt: "小正方形", semanticSegments: ["小正方形"] }
    ],
    correctOptionId: "largeCircle",
    distractorRationale: "小圓形過早重置尺寸；大正方形未維持圓形組別；小正方形形狀尺寸皆錯。",
    measurementTarget: "週期性尺寸遞增與形狀群組變化。",
    internalExplanation: "正方形組歷經小、中、大；圓形組接續小、中，因此下一項為大圓形。",
    suggestedTimeSeconds: 11,
    provisionalA: 1.0,
    provisionalB: -0.2,
    provisionalC: 0.25,
    accessibilityAlt: "序列為小正方形、中正方形、大正方形、小圓形、中圓形、問號。",
  },
  {
    id: "q15", category: "verbal", difficulty: "easy",
    stem: "下列哪一個項目，與其他三者屬於不同類別？",
    semanticSegments: ["下列哪一個項目，", "與其他三者屬於不同類別？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "brush", alt: "畫筆", semanticSegments: ["畫筆"] },
      { id: "piano", alt: "鋼琴", semanticSegments: ["鋼琴"] },
      { id: "violin", alt: "小提琴", semanticSegments: ["小提琴"] },
      { id: "guitar", alt: "吉他", semanticSegments: ["吉他"] }
    ],
    correctOptionId: "brush",
    distractorRationale: "鋼琴、小提琴、吉他皆為樂器，唯獨畫筆為繪畫美術工具。",
    measurementTarget: "概念屬性分類與排除例外。",
    internalExplanation: "其他三者均為音樂演奏樂器，畫筆屬於視覺藝術繪畫用具，類別不同。",
    suggestedTimeSeconds: 10,
    provisionalA: 0.9,
    provisionalB: -0.15,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q16", category: "processingSpeed", difficulty: "easy",
    stem: "陣列中，唯一「缺口朝左」的符號位於哪一格？",
    semanticSegments: ["陣列中，", "唯一「缺口朝左」的符號", "位於哪一格？"],
    stimulus: {"kind": "visual", "visualKey": "search-gap-left-easy"},
    options: [
      { id: "r2c3", alt: "第 2 列第 3 格", semanticSegments: ["第 2 列第 3 格"] },
      { id: "r1c2", alt: "第 1 列第 2 格", semanticSegments: ["第 1 列第 2 格"] },
      { id: "r3c1", alt: "第 3 列第 1 格", semanticSegments: ["第 3 列第 1 格"] },
      { id: "r4c4", alt: "第 4 列第 4 格", semanticSegments: ["第 4 列第 4 格"] }
    ],
    correctOptionId: "r2c3",
    distractorRationale: "其餘選項均為缺口朝上或朝右的干擾符號。",
    measurementTarget: "方向特徵視覺搜尋與快速定位。",
    internalExplanation: "在 4x4 陣列中，只有第 2 列第 3 格缺口明確朝左，其餘皆朝其他方向。",
    suggestedTimeSeconds: 10,
    provisionalA: 1.0,
    provisionalB: -0.1,
    provisionalC: 0.25,
    accessibilityAlt: "四乘四缺口圓形陣列，尋找唯一缺口朝左之目標格。",
  },
  {
    id: "q17", category: "verbal", difficulty: "medium",
    stem: "前言和文章的關係，就像序曲和什麼？",
    semanticSegments: ["前言和文章的關係，", "就像序曲和什麼？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "music", alt: "樂曲", semanticSegments: ["樂曲"] },
      { id: "instrument", alt: "樂器", semanticSegments: ["樂器"] },
      { id: "stage", alt: "舞台", semanticSegments: ["舞台"] },
      { id: "composer", alt: "作曲家", semanticSegments: ["作曲家"] }
    ],
    correctOptionId: "music",
    distractorRationale: "樂器是演奏工具；舞台是演出場所；作曲家是創作者，皆非序曲引介的完整作品本身。",
    measurementTarget: "前導部分與作品整體的關係類比。",
    internalExplanation: "前言是文章開頭的引介篇章，序曲是整部樂曲開頭的引介樂段。",
    suggestedTimeSeconds: 13,
    provisionalA: 1.05,
    provisionalB: -0.05,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q18", category: "spatial", difficulty: "medium",
    stem: "圖形順時針旋轉 90° 後，哪個結果正確？",
    semanticSegments: ["圖形", "順時針旋轉 90° 後，", "哪個結果正確？"],
    stimulus: {"kind": "visual", "visualKey": "rotate-hook-medium"},
    options: [
      { id: "correct", alt: "順時針旋轉九十度後的鉤形與圓點", visualKey: "hook-rotate-correct" },
      { id: "wrong", alt: "只移動圓點但未正確旋轉的鉤形", visualKey: "hook-rotate-wrong" },
      { id: "counter", alt: "逆時針旋轉九十度後的鉤形與圓點", visualKey: "hook-rotate-counter" },
      { id: "half", alt: "旋轉一百八十度後的鉤形與圓點", visualKey: "hook-rotate-half" }
    ],
    correctOptionId: "correct",
    distractorRationale: "只移動圓點漏做本體旋轉；其餘分別使用相反旋向或錯誤 180 度旋轉角度。",
    measurementTarget: "不對稱複合圖形之 90 度心智旋轉。",
    internalExplanation: "主體鉤形與附著圓點皆繞圖形中心順時針旋轉 90 度。",
    suggestedTimeSeconds: 16,
    provisionalA: 1.15,
    provisionalB: 0.05,
    provisionalC: 0.25,
    accessibilityAlt: "不對稱鉤形與圓點，旁邊標示順時針九十度。",
  },
  {
    id: "q19", category: "quantitative", difficulty: "medium",
    stem: "依照規則，下一個數字是？",
    semanticSegments: ["依照規則，", "下一個數字是？"],
    stimulus: {"kind": "sequence", "values": ["2", "5", "11", "23", "？"]},
    options: [
      { id: "fortySeven", alt: "47", semanticSegments: ["47"] },
      { id: "fortySix", alt: "46", semanticSegments: ["46"] },
      { id: "fortyFive", alt: "45", semanticSegments: ["45"] },
      { id: "fortyEight", alt: "48", semanticSegments: ["48"] }
    ],
    correctOptionId: "fortySeven",
    distractorRationale: "46 只乘二漏加一；45 誤作乘二減一；48 做乘二加二。",
    measurementTarget: "乘二加一之遞迴數列。",
    internalExplanation: "遞迴規則為每項乘以 2 再加 1：23 × 2 + 1 = 47。",
    suggestedTimeSeconds: 16,
    provisionalA: 1.2,
    provisionalB: 0.1,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 2、5、11、23、問號。",
  },
  {
    id: "q20", category: "abstract", difficulty: "medium",
    stem: "形狀與填色各有規則，下一個圖形是？",
    semanticSegments: ["形狀與填色各有規則，", "下一個圖形是？"],
    stimulus: {"kind": "visual", "visualKey": "shape-fill-cycle"},
    options: [
      { id: "filled", alt: "實心正方形", visualKey: "option-square-filled" },
      { id: "outline", alt: "空心正方形", visualKey: "option-square-outline" },
      { id: "outlineCircle", alt: "空心圓形", visualKey: "option-circle-outline" },
      { id: "filledTriangle", alt: "實心三角形", visualKey: "option-triangle-filled" }
    ],
    correctOptionId: "filled",
    distractorRationale: "空心正方形漏掉填色交替；空心圓重置形狀過早；實心三角形停滯在前一形狀。",
    measurementTarget: "雙維度追蹤：形狀成對推進與填色交替。",
    internalExplanation: "形狀為圓兩次、三角形兩次、正方形兩次；填色為空心、實心輪替。正方形第一項為空心，故第二項為實心正方形。",
    suggestedTimeSeconds: 17,
    provisionalA: 1.25,
    provisionalB: 0.15,
    provisionalC: 0.25,
    accessibilityAlt: "空心圓、實心圓、空心三角形、實心三角形、空心正方形、問號。",
  },
  {
    id: "q21", category: "logic", difficulty: "medium",
    stem: "根據三個條件，哪個結論必然成立？",
    semanticSegments: ["根據三個條件，", "哪個結論必然成立？"],
    stimulus: {"kind": "logic", "lines": [["所有 A 都是 B"], ["沒有 B 是 C"], ["有些 D 是 A"]]},
    options: [
      { id: "some", alt: "有些 D 不是 C", semanticSegments: ["有些 D 不是 C"] },
      { id: "reverse", alt: "有些 C 是 D", semanticSegments: ["有些 C 是 D"] },
      { id: "allD", alt: "所有 D 都不是 C", semanticSegments: ["所有 D 都不是 C"] },
      { id: "someC", alt: "有些 A 是 C", semanticSegments: ["有些 A 是 C"] }
    ],
    correctOptionId: "some",
    distractorRationale: "有些 C 是 D 無法保證存在交集；所有 D 都不是 C 過度推論（非 A 之 D 可能在 C）；有些 A 是 C 直接違反互斥。",
    measurementTarget: "集合包容、互斥與存在量詞演繹。",
    internalExplanation: "存在元素既是 D 又是 A；該元素屬於 A 故屬於 B；又 B 與 C 完全互斥，故該元素絕不在 C 中，因此必然有些 D 不是 C。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.25,
    provisionalB: 0.2,
    provisionalC: 0.25,
    accessibilityAlt: "三行集合條件，A、B、C、D 為中性類別代號。",
  },
  {
    id: "q22", category: "workingMemory", difficulty: "medium",
    stem: "取出偶數並保持原順序，再倒過來。第一個數字是？",
    semanticSegments: ["取出偶數並", "保持原順序，", "再倒過來。", "第一個數字是？"],
    stimulus: {"kind": "memory", "values": ["8", "F", "5", "2", "K"], "durationMs": 9500},
    options: [
      { id: "two", alt: "2", semanticSegments: ["2"] },
      { id: "eight", alt: "8", semanticSegments: ["8"] },
      { id: "five", alt: "5", semanticSegments: ["5"] },
      { id: "f", alt: "F", semanticSegments: ["F"] }
    ],
    correctOptionId: "two",
    distractorRationale: "8 為原順序中第一項（漏掉倒序）；5 為奇數干擾；F 為字母干擾。",
    measurementTarget: "混合序列屬性篩選、次序保持與倒序操作。",
    internalExplanation: "數列中偶數依序為 8、2；倒序後為 2、8，故第一個數字是 2。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.25,
    provisionalB: 0.25,
    provisionalC: 0.25,
    accessibilityAlt: "先短暫顯示 8、F、5、2、K，接著隱藏。",
  },
  {
    id: "q23", category: "processingSpeed", difficulty: "medium",
    stem: "右上箭頭共有幾個？",
    semanticSegments: ["右上箭頭", "共有幾個？"],
    stimulus: {"kind": "visual", "visualKey": "search-arrows-medium"},
    options: [
      { id: "five", alt: "5 個", semanticSegments: ["5 個"] },
      { id: "six", alt: "6 個", semanticSegments: ["6 個"] },
      { id: "four", alt: "4 個", semanticSegments: ["4 個"] },
      { id: "seven", alt: "7 個", semanticSegments: ["7 個"] }
    ],
    correctOptionId: "five",
    distractorRationale: "6 與 7 把相鄰右方或上方箭頭誤計入；4 漏查角落項目。",
    measurementTarget: "二維方向特徵密集視覺搜尋與精確計數。",
    internalExplanation: "五乘五陣列中，指向東北（45度右上）之箭頭恰好有 5 個。",
    suggestedTimeSeconds: 10,
    provisionalA: 1.1,
    provisionalB: 0.3,
    provisionalC: 0.25,
    accessibilityAlt: "五乘五箭頭陣列，其中右上箭頭有五個。",
  },
  {
    id: "q24", category: "spatial", difficulty: "medium",
    stem: "把紙網摺成立方體後，哪一面與 A 相對？",
    semanticSegments: ["把紙網摺成立方體後，", "哪一面與 A 相對？"],
    stimulus: {"kind": "visual", "visualKey": "cube-net-medium"},
    options: [
      { id: "c", alt: "C 面", semanticSegments: ["C 面"] },
      { id: "d", alt: "D 面", semanticSegments: ["D 面"] },
      { id: "e", alt: "E 面", semanticSegments: ["E 面"] },
      { id: "f", alt: "F 面", semanticSegments: ["F 面"] }
    ],
    correctOptionId: "c",
    distractorRationale: "D 面與 A 緊鄰；E 與 F 面摺起後為左右兩側面，皆非 A 之相對底面。",
    measurementTarget: "立方體展開紙網的空間摺疊與相對面判斷。",
    internalExplanation: "垂直四聯方為 A、D、C、B；相隔一面之 A 與 C 摺疊成立方體後分居前後相對兩面。",
    suggestedTimeSeconds: 19,
    provisionalA: 1.3,
    provisionalB: 0.35,
    provisionalC: 0.25,
    accessibilityAlt: "六格立方體紙網，中央為 C，上方依序為 D、A，下方為 B，左右為 E、F。",
  },
  {
    id: "q25", category: "verbal", difficulty: "medium",
    stem: "種子變成植物，就像哪一組？",
    semanticSegments: ["種子變成植物，", "就像哪一組？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "egg", alt: "卵變成動物", semanticSegments: ["卵變成動物"] },
      { id: "milk", alt: "牛奶變成乳酪", semanticSegments: ["牛奶變成乳酪"] },
      { id: "clay", alt: "黏土變成陶器", semanticSegments: ["黏土變成陶器"] },
      { id: "ice", alt: "水變成冰塊", semanticSegments: ["水變成冰塊"] }
    ],
    correctOptionId: "egg",
    distractorRationale: "牛奶加工變乳酪與黏土燒陶為人工加工，水成冰為物理相變，皆非生物自發發育生長。",
    measurementTarget: "自然發育演變與人為加工/相變之本質區分。",
    internalExplanation: "種子透過生命發育長成成熟植物，卵透過胚胎發育長成成熟動物，同屬生物個體發育關係。",
    suggestedTimeSeconds: 14,
    provisionalA: 1.1,
    provisionalB: 0.4,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q26", category: "quantitative", difficulty: "medium",
    stem: "同一個對應規則下，5 對應到多少？",
    semanticSegments: ["同一個對應規則下，", "5 對應到多少？"],
    stimulus: {"kind": "mapping", "pairs": ["2 → 6", "3 → 12", "4 → 20", "5 → ？"]},
    options: [
      { id: "thirty", alt: "30", semanticSegments: ["30"] },
      { id: "twentyFive", alt: "25", semanticSegments: ["25"] },
      { id: "twentyFour", alt: "24", semanticSegments: ["24"] },
      { id: "thirtyFive", alt: "35", semanticSegments: ["35"] }
    ],
    correctOptionId: "thirty",
    distractorRationale: "25 只做平方 n×n；24 沿用前一步差值 (+8)；35 誤乘以下一個奇數。",
    measurementTarget: "由數對關係抽取 n × (n + 1) 之代數結構。",
    internalExplanation: "每項映射為輸入乘以下一個連續整數：2×3=6, 3×4=12, 4×5=20，因此 5 對應 5×6 = 30。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.3,
    provisionalB: 0.45,
    provisionalC: 0.25,
    accessibilityAlt: "對應為 2 到 6、3 到 12、4 到 20、5 到問號。",
  },
  {
    id: "q27", category: "abstract", difficulty: "medium",
    stem: "每列前兩格疊在一起形成第三格。缺少哪一格？",
    semanticSegments: ["每列前兩格疊在一起", "形成第三格。", "缺少哪一格？"],
    stimulus: {"kind": "visual", "visualKey": "matrix-overlay"},
    options: [
      { id: "diagonal", alt: "只包含叉形線", visualKey: "overlay-diagonal" },
      { id: "cross", alt: "只包含十字線", visualKey: "overlay-cross" },
      { id: "both", alt: "同時包含十字與叉形線", visualKey: "overlay-both" },
      { id: "empty", alt: "不包含任何線", visualKey: "overlay-empty" }
    ],
    correctOptionId: "diagonal",
    distractorRationale: "十字線誤套第一列線條；同時包含則未依據第二列輸入；空白將聯集誤作互消。",
    measurementTarget: "矩陣元素幾何線條聯集合成推理。",
    internalExplanation: "第二列第一格為左上至右下斜線，第二格為右上至左下斜線，兩者疊加形成叉形線（X形）。",
    suggestedTimeSeconds: 19,
    provisionalA: 1.25,
    provisionalB: 0.5,
    provisionalC: 0.25,
    accessibilityAlt: "矩陣每列第三格為前兩格線條疊加，最後一格缺少。",
  },
  {
    id: "q28", category: "logic", difficulty: "medium",
    stem: "如果警報開啟，指示燈就會閃。現在指示燈沒有閃。警報狀態是？",
    semanticSegments: ["如果警報開啟，", "指示燈就會閃。", "現在指示燈沒有閃。", "警報狀態是？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "off", alt: "必然未開啟", semanticSegments: ["必然未開啟"] },
      { id: "unknown", alt: "無法判斷", semanticSegments: ["無法判斷"] },
      { id: "on", alt: "必然已開啟", semanticSegments: ["必然已開啟"] },
      { id: "broken", alt: "指示燈必然故障", semanticSegments: ["指示燈必然故障"] }
    ],
    correctOptionId: "off",
    distractorRationale: "無法判斷忽略充分條件假言命題逆否性；必然已開啟顛倒命題；故障加入非題幹假設。",
    measurementTarget: "假言命題否定後件律（Modus Tollens）。",
    internalExplanation: "若 P 則 Q；非 Q 則必然非 P。指示燈未閃爍，故警報必然未開啟。",
    suggestedTimeSeconds: 16,
    provisionalA: 1.2,
    provisionalB: 0.55,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q29", category: "workingMemory", difficulty: "medium",
    stem: "只取出字母，再倒過來。中間的字母是？",
    semanticSegments: ["只取出字母，", "再倒過來。", "中間的字母是？"],
    stimulus: {"kind": "memory", "values": ["B", "3", "F", "8", "D"], "durationMs": 10000},
    options: [
      { id: "f", alt: "F", semanticSegments: ["F"] },
      { id: "d", alt: "D", semanticSegments: ["D"] },
      { id: "b", alt: "B", semanticSegments: ["B"] },
      { id: "three", alt: "3", semanticSegments: ["3"] }
    ],
    correctOptionId: "f",
    distractorRationale: "D 是倒序後第 1 項；B 是倒序後末項；3 為被篩除的數字干擾。",
    measurementTarget: "跨類別過濾、倒序與中心定位操作。",
    internalExplanation: "原數列字母為 B、F、D；倒序後為 D、F、B，中間項依然為 F。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.3,
    provisionalB: 0.6,
    provisionalC: 0.25,
    accessibilityAlt: "先短暫顯示 B、3、F、8、D，接著隱藏。",
  },
  {
    id: "q30", category: "quantitative", difficulty: "medium",
    stem: "兩種運算輪流出現。下一個數字是？",
    semanticSegments: ["兩種運算輪流出現。", "下一個數字是？"],
    stimulus: {"kind": "sequence", "values": ["1", "2", "6", "7", "21", "22", "？"]},
    options: [
      { id: "sixtySix", alt: "66", semanticSegments: ["66"] },
      { id: "sixtyFour", alt: "64", semanticSegments: ["64"] },
      { id: "sixtySeven", alt: "67", semanticSegments: ["67"] },
      { id: "fortyFour", alt: "44", semanticSegments: ["44"] }
    ],
    correctOptionId: "sixtySix",
    distractorRationale: "64 未維持加一乘三規律；67 重複做加一；44 誤作乘二。",
    measurementTarget: "交替雙步運算（+1, ×3）數列規律追蹤。",
    internalExplanation: "運算序列為 +1, ×3, +1, ×3, +1, ×3。22 之後輪到乘以 3：22 × 3 = 66。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.35,
    provisionalB: 0.65,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 1、2、6、7、21、22、問號。",
  },
  {
    id: "q31", category: "abstract", difficulty: "medium",
    stem: "平面網格中，質點依規律移動：由 (1, 1) 開始，每步依向量 (＋2, ＋1) 移動。第 3 步之後的座標是？",
    semanticSegments: ["平面網格中，", "質點依規律移動：", "由 (1, 1) 開始，", "每步依向量 (＋2, ＋1) 移動。", "第 3 步之後的座標是？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "c74", alt: "(7, 4)", semanticSegments: ["(7, 4)"] },
      { id: "c53", alt: "(5, 3)", semanticSegments: ["(5, 3)"] },
      { id: "c64", alt: "(6, 4)", semanticSegments: ["(6, 4)"] },
      { id: "c85", alt: "(8, 5)", semanticSegments: ["(8, 5)"] }
    ],
    correctOptionId: "c74",
    distractorRationale: "(5, 3) 少走一步只算到第 2 步；(6, 4) 水平座標算錯；(8, 5) 誤算為 4 步。",
    measurementTarget: "二維座標向量規律累加與線性外推能力。",
    internalExplanation: "起始 (1, 1)，每步加 (2, 1)：第 1 步 (3, 2)、第 2 步 (5, 3)、第 3 步 (7, 4)。",
    suggestedTimeSeconds: 15,
    provisionalA: 1.2,
    provisionalB: 0.7,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形；座標為（水平, 垂直）。",
  },
  {
    id: "q32", category: "processingSpeed", difficulty: "medium",
    stem: "上下兩列符號中，有幾處相對應位置的符號完全相異？",
    semanticSegments: ["上下兩列符號中，", "有幾處相對應位置的符號", "完全相異？"],
    stimulus: {"kind": "textRows", "rows": ["▲■●★◆▲■●", "▲■◆★●▲■●"]},
    options: [
      { id: "twoDiff", alt: "2 處", semanticSegments: ["2 處"] },
      { id: "oneDiff", alt: "1 處", semanticSegments: ["1 處"] },
      { id: "threeDiff", alt: "3 處", semanticSegments: ["3 處"] },
      { id: "fourDiff", alt: "4 處", semanticSegments: ["4 處"] }
    ],
    correctOptionId: "twoDiff",
    distractorRationale: "1 處漏看第 5 位的相異；3 處誤把第 4 位相同符號計入；4 處重複計數兩對位置。",
    measurementTarget: "八位元幾何符號序列逐項平行校驗與相異計數。",
    internalExplanation: "逐項比對：第 3 位（● 與 ◆）與第 5 位（◆ 與 ●）相異，其餘 6 個位置皆完全相同，共有 2 處相異。",
    suggestedTimeSeconds: 11,
    provisionalA: 1.15,
    provisionalB: 0.75,
    provisionalC: 0.25,
    accessibilityAlt: "兩列八符號代碼，逐位比對相異處數量。",
  },
  {
    id: "q33", category: "abstract", difficulty: "medium",
    stem: "觀察二乘二矩陣，右下角應該是？",
    semanticSegments: ["觀察二乘二矩陣，", "右下角應該是？"],
    stimulus: {"kind": "visual", "visualKey": "matrix-lines-medium"},
    options: [
      { id: "opt2Vert", alt: "2 條直線", semanticSegments: ["2 條直線"] },
      { id: "opt1Vert", alt: "1 條直線", semanticSegments: ["1 條直線"] },
      { id: "opt2Hori", alt: "2 條橫線", semanticSegments: ["2 條橫線"] },
      { id: "opt3Vert", alt: "3 條直線", semanticSegments: ["3 條直線"] }
    ],
    correctOptionId: "opt2Vert",
    distractorRationale: "1 條直線未完成數量遞增；2 條橫線混淆列方向規則；3 條直線過度遞增。",
    measurementTarget: "方向恆常與數量列遞增的雙重二維規則。",
    internalExplanation: "第一列為橫線，數量由 1 增至 2；第二列為直線，數量由 1 增至 2，故缺格為 2 條直線。",
    suggestedTimeSeconds: 14,
    provisionalA: 1.2,
    provisionalB: 0.8,
    provisionalC: 0.25,
    accessibilityAlt: "二乘二矩陣：第一列為一條橫線、兩條橫線；第二列為一條直線、缺格。",
  },
  {
    id: "q34", category: "logic", difficulty: "medium",
    stem: "甲、乙、丙、丁四人比身高：甲比乙高，丙比甲高，丁比乙矮。四人中誰最矮？",
    semanticSegments: ["甲、乙、丙、丁四人比身高：", "甲比乙高，", "丙比甲高，", "丁比乙矮。", "四人中誰最矮？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "d", alt: "丁", semanticSegments: ["丁"] },
      { id: "b", alt: "乙", semanticSegments: ["乙"] },
      { id: "a", alt: "甲", semanticSegments: ["甲"] },
      { id: "c", alt: "丙", semanticSegments: ["丙"] }
    ],
    correctOptionId: "d",
    distractorRationale: "乙比丁高並非最矮；甲與丙分別高於乙與甲，居前段排位。",
    measurementTarget: "多元全序傳遞關係推理。",
    internalExplanation: "由條件得：丙 > 甲 > 乙 > 丁，因此丁最矮，順序完全確定。",
    suggestedTimeSeconds: 14,
    provisionalA: 1.2,
    provisionalB: 0.85,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q35", category: "workingMemory", difficulty: "medium",
    stem: "剛才出現的項目中，第 4 個項目是？",
    semanticSegments: ["剛才出現的項目中，", "第 4 個項目是？"],
    stimulus: {"kind": "memory", "values": ["M", "7", "X", "3", "B", "9"], "durationMs": 9500},
    options: [
      { id: "three", alt: "3", semanticSegments: ["3"] },
      { id: "x", alt: "X", semanticSegments: ["X"] },
      { id: "b", alt: "B", semanticSegments: ["B"] },
      { id: "seven", alt: "7", semanticSegments: ["7"] }
    ],
    correctOptionId: "three",
    distractorRationale: "X 是第 3 個；B 是第 5 個；7 是第 2 個。",
    measurementTarget: "六項混合文字數字序列順序定位。",
    internalExplanation: "原順序為：1:M, 2:7, 3:X, 4:3, 5:B, 6:9，第四項為 3。",
    suggestedTimeSeconds: 15,
    provisionalA: 1.25,
    provisionalB: 0.9,
    provisionalC: 0.25,
    accessibilityAlt: "先短暫顯示 M、7、X、3、B、9，接著隱藏。",
  },
  {
    id: "q36", category: "quantitative", difficulty: "medium",
    stem: "運算規律交替進行，下一個數字是？",
    semanticSegments: ["運算規律交替進行，", "下一個數字是？"],
    stimulus: {"kind": "sequence", "values": ["3", "6", "5", "10", "9", "18", "17", "？"]},
    options: [
      { id: "thirtyFour", alt: "34", semanticSegments: ["34"] },
      { id: "thirtyFive", alt: "35", semanticSegments: ["35"] },
      { id: "eighteen", alt: "18", semanticSegments: ["18"] },
      { id: "thirtyTwo", alt: "32", semanticSegments: ["32"] }
    ],
    correctOptionId: "thirtyFour",
    distractorRationale: "35 錯做加法；18 停滯在前值；32 減二運算錯誤。",
    measurementTarget: "雙交替運算（×2, -1）數列推理。",
    internalExplanation: "運算依序為 ×2, -1, ×2, -1, ×2, -1, ×2。17 之後需乘以 2：17 × 2 = 34。",
    suggestedTimeSeconds: 16,
    provisionalA: 1.25,
    provisionalB: 0.95,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 3、6、5、10、9、18、17、問號。",
  },
  {
    id: "q37", category: "logic", difficulty: "medium",
    stem: "五人排隊買票：D 排在最前面，A 排在 B 前面，C 排在 A 前面，E 排在 B 後面。誰排在最後面？",
    semanticSegments: ["五人排隊買票：", "D 排在最前面，", "A 排在 B 前面，", "C 排在 A 前面，", "E 排在 B 後面。", "誰排在最後面？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "e", alt: "E", semanticSegments: ["E"] },
      { id: "b", alt: "B", semanticSegments: ["B"] },
      { id: "a", alt: "A", semanticSegments: ["A"] },
      { id: "c", alt: "C", semanticSegments: ["C"] }
    ],
    correctOptionId: "e",
    distractorRationale: "B 是倒數第 2 個；A 排在第 3 位；C 排在第 2 位。",
    measurementTarget: "多元全序偏序傳遞關係整合與末位判定。",
    internalExplanation: "由條件排序：D（第1）→ C（第2）→ A（第3）→ B（第4）→ E（第5），最後一名必然是 E。",
    suggestedTimeSeconds: 14,
    provisionalA: 1.25,
    provisionalB: 1.0,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q38", category: "verbal", difficulty: "medium",
    stem: "溫度計之於氣溫，就像天平之於什麼？",
    semanticSegments: ["溫度計之於氣溫，", "就像天平之於什麼？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "mass", alt: "質量", semanticSegments: ["質量"] },
      { id: "speed", alt: "速度", semanticSegments: ["速度"] },
      { id: "length", alt: "長度", semanticSegments: ["長度"] },
      { id: "volume", alt: "體積", semanticSegments: ["體積"] }
    ],
    correctOptionId: "mass",
    distractorRationale: "速度使用測速儀；長度使用直尺；體積使用量筒，皆非天平之測量標的。",
    measurementTarget: "測量儀器與對應物理量之功能映射。",
    internalExplanation: "溫度計是用於測量氣溫的工具，天平是用於測量物體質量的工具。",
    suggestedTimeSeconds: 12,
    provisionalA: 1.15,
    provisionalB: 1.05,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q39", category: "abstract", difficulty: "medium",
    stem: "三種幾何圖形循環出現，下一個圖形是？",
    semanticSegments: ["三種幾何圖形循環出現，", "下一個圖形是？"],
    stimulus: {"kind": "sequence", "values": ["△", "○", "□", "△", "○", "□", "△", "？"]},
    options: [
      { id: "circle", alt: "○", semanticSegments: ["○"] },
      { id: "square", alt: "□", semanticSegments: ["□"] },
      { id: "triangle", alt: "△", semanticSegments: ["△"] },
      { id: "star", alt: "★", semanticSegments: ["★"] }
    ],
    correctOptionId: "circle",
    distractorRationale: "□ 順序過早跳位；△ 連續重複；★ 不在循環集合中。",
    measurementTarget: "模 3 序列之週期循環追蹤。",
    internalExplanation: "序列以 △、○、□ 為固定 3 項循環，△ 之後必然接續 ○。",
    suggestedTimeSeconds: 11,
    provisionalA: 1.1,
    provisionalB: 1.1,
    provisionalC: 0.25,
    accessibilityAlt: "序列為 △、○、□、△、○、□、△、問號。",
  },
  {
    id: "q40", category: "logic", difficulty: "medium",
    stem: "週末如果下雨，就去圖書館。如果沒有下雨，就去運動場。這個週末沒有下雨。由此可必然得出？",
    semanticSegments: ["週末如果下雨，就去圖書館。", "如果沒有下雨，就去運動場。", "這個週末沒有下雨。", "由此可必然得出？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "stadium", alt: "週末去運動場", semanticSegments: ["週末去運動場"] },
      { id: "library", alt: "週末去圖書館", semanticSegments: ["週末去圖書館"] },
      { id: "home", alt: "留在家中", semanticSegments: ["留在家中"] },
      { id: "uncertain", alt: "無法確定去哪裡", semanticSegments: ["無法確定去哪裡"] }
    ],
    correctOptionId: "stadium",
    distractorRationale: "圖書館為下雨時的去處；留在家中加入無關條件；無法確定忽略前件已真之必然性。",
    measurementTarget: "二難互斥假言命題之肯定前件推理。",
    internalExplanation: "前提明確給定「沒有下雨則去運動場」；現已知沒有下雨，直接肯定前件得出去運動場。",
    suggestedTimeSeconds: 14,
    provisionalA: 1.2,
    provisionalB: 1.15,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q41", category: "processingSpeed", difficulty: "medium",
    stem: "符號陣列中，「★」符號共有幾個？",
    semanticSegments: ["符號陣列中，", "「★」符號共有幾個？"],
    stimulus: {"kind": "visual", "visualKey": "search-star-medium"},
    options: [
      { id: "six", alt: "6 個", semanticSegments: ["6 個"] },
      { id: "five", alt: "5 個", semanticSegments: ["5 個"] },
      { id: "seven", alt: "7 個", semanticSegments: ["7 個"] },
      { id: "four", alt: "4 個", semanticSegments: ["4 個"] }
    ],
    correctOptionId: "six",
    distractorRationale: "5 與 4 漏查邊緣；7 誤將相似星號或四角星重複計入。",
    measurementTarget: "高密度異質符號陣列之精準視覺搜尋計數。",
    internalExplanation: "在五乘五陣列中，黑色五角星符號 ★ 出現數量精確為 6 個。",
    suggestedTimeSeconds: 11,
    provisionalA: 1.2,
    provisionalB: 1.2,
    provisionalC: 0.25,
    accessibilityAlt: "五乘五符號陣列，計算 ★ 符號總數。",
  },
  {
    id: "q42", category: "workingMemory", difficulty: "medium",
    stem: "三乘三九宮格中，剛才哪一格有圓點？",
    semanticSegments: ["三乘三九宮格中，", "剛才哪一格有圓點？"],
    stimulus: {"kind": "memory", "values": ["第 1 列第 3 格", "第 2 列第 2 格"], "durationMs": 10500},
    options: [
      { id: "r1c3", alt: "第 1 列第 3 格", semanticSegments: ["第 1 列第 3 格"] },
      { id: "r1c1", alt: "第 1 列第 1 格", semanticSegments: ["第 1 列第 1 格"] },
      { id: "r3c3", alt: "第 3 列第 3 格", semanticSegments: ["第 3 列第 3 格"] },
      { id: "r2c1", alt: "第 2 列第 1 格", semanticSegments: ["第 2 列第 1 格"] }
    ],
    correctOptionId: "r1c3",
    distractorRationale: "其餘三格在刺激呈現時皆為純白空格，並無圓點。",
    measurementTarget: "空間二維位置短暫保持與再認回憶。",
    internalExplanation: "刺激呈現時，圓點僅位於第 1 列第 3 格（右上角）與第 2 列第 2 格（中心），選項中只有第 1 列第 3 格正確。",
    suggestedTimeSeconds: 16,
    provisionalA: 1.25,
    provisionalB: 1.25,
    provisionalC: 0.25,
    accessibilityAlt: "先在九宮格中顯示第 1 列第 3 格與第 2 列第 2 格之圓點，接著隱藏。",
  },
  {
    id: "q43", category: "quantitative", difficulty: "medium",
    stem: "觀察分數數列規律，下一個分數是？",
    semanticSegments: ["觀察分數數列規律，", "下一個分數是？"],
    stimulus: {"kind": "sequence", "values": ["1/2", "2/3", "3/4", "4/5", "？"]},
    options: [
      { id: "fiveSixths", alt: "5/6", semanticSegments: ["5/6"] },
      { id: "fourSixths", alt: "4/6", semanticSegments: ["4/6"] },
      { id: "fiveSevenths", alt: "5/7", semanticSegments: ["5/7"] },
      { id: "sixSevenths", alt: "6/7", semanticSegments: ["6/7"] }
    ],
    correctOptionId: "fiveSixths",
    distractorRationale: "4/6 分子未增加；5/7 分母多跳了一號；6/7 整體超前兩階。",
    measurementTarget: "有理數分子分母聯立等差數列規律。",
    internalExplanation: "分子為 1, 2, 3, 4, 5；分母為 2, 3, 4, 5, 6，下一項必然為 5/6。",
    suggestedTimeSeconds: 14,
    provisionalA: 1.25,
    provisionalB: 1.3,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 1/2、2/3、3/4、4/5、問號。",
  },
  {
    id: "q44", category: "spatial", difficulty: "medium",
    stem: "英文字母「F」順時針旋轉 180° 後，形狀外觀為？",
    semanticSegments: ["英文字母「F」", "順時針旋轉 180° 後，", "形狀外觀為？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "fRot180", alt: "豎線在右側，兩橫線朝左下方延伸", semanticSegments: ["豎線在右側，兩橫線朝左下方延伸"] },
      { id: "fMirror", alt: "豎線在右側，兩橫線朝左上方延伸", semanticSegments: ["豎線在右側，兩橫線朝左上方延伸"] },
      { id: "fFlip", alt: "豎線在左側，兩橫線朝右下方延伸", semanticSegments: ["豎線在左側，兩橫線朝右下方延伸"] },
      { id: "fRot90", alt: "豎線呈水平，兩橫線朝正下方延伸", semanticSegments: ["豎線呈水平，兩橫線朝正下方延伸"] }
    ],
    correctOptionId: "fRot180",
    distractorRationale: "鏡像只做左右反轉；上下顛倒只做垂直反射；旋轉 90 度角度不足。",
    measurementTarget: "非對稱平面字符之 180 度點對稱心智旋轉。",
    internalExplanation: "F 繞中心轉 180 度等同中心對稱：豎線移至右側，上下兩橫線倒立並指向左側下方。",
    suggestedTimeSeconds: 15,
    provisionalA: 1.25,
    provisionalB: 1.35,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q45", category: "verbal", difficulty: "medium",
    stem: "下列哪一組詞的關係，與「醫生：醫院」的本質最不相符？",
    semanticSegments: ["下列哪一組詞的關係，", "與「醫生：醫院」的本質最不相符？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "driverPassenger", alt: "司機：乘客", semanticSegments: ["司機：乘客"] },
      { id: "teacherSchool", alt: "教師：學校", semanticSegments: ["教師：學校"] },
      { id: "judgeCourt", alt: "法官：法院", semanticSegments: ["法官：法院"] },
      { id: "chefRestaurant", alt: "廚師：餐廳", semanticSegments: ["廚師：餐廳"] }
    ],
    correctOptionId: "driverPassenger",
    distractorRationale: "其他三者均為「專業從業者：專屬執業場所」，司機之於乘客為服務對象關係。",
    measurementTarget: "職業與工作場所之特定關係分類與異常排除。",
    internalExplanation: "教師在學校、法官在法院、廚師在餐廳皆為人員與場所關係，司機與乘客是人與人之互動關係，本質不同。",
    suggestedTimeSeconds: 13,
    provisionalA: 1.2,
    provisionalB: 1.4,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q46", category: "abstract", difficulty: "medium",
    stem: "二乘二矩陣中，每格的邊數遵循規律：第一列為 3 邊形、4 邊形；第二列為 5 邊形、缺格。缺格應為幾邊形？",
    semanticSegments: ["二乘二矩陣中，", "每格的邊數遵循規律：", "第一列為 3 邊形、4 邊形；", "第二列為 5 邊形、缺格。", "缺格應為幾邊形？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "six", alt: "6 邊形", semanticSegments: ["6 邊形"] },
      { id: "five", alt: "5 邊形", semanticSegments: ["5 邊形"] },
      { id: "seven", alt: "7 邊形", semanticSegments: ["7 邊形"] },
      { id: "eight", alt: "8 邊形", semanticSegments: ["8 邊形"] }
    ],
    correctOptionId: "six",
    distractorRationale: "5 邊形停滯未加；7 邊形超前加二；8 邊形誤算加倍。",
    measurementTarget: "矩陣行與列多邊形邊數雙重等差規律。",
    internalExplanation: "橫向每步邊數加 1：3 到 4；5 到 6，故缺格應為 6 邊形（縱向亦符合 3 到 5、4 到 6 之加 2 規律）。",
    suggestedTimeSeconds: 13,
    provisionalA: 1.2,
    provisionalB: 1.45,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q47", category: "logic", difficulty: "medium",
    stem: "如果小明通過考試，他就獲得證書。如果他獲得證書，他就能開始實習。事實上小明現在「不能開始實習」。由此可必然得出？",
    semanticSegments: ["如果小明通過考試，他就獲得證書。", "如果他獲得證書，他就能開始實習。", "事實上小明現在「不能開始實習」。", "由此可必然得出？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "failed", alt: "小明沒有通過考試", semanticSegments: ["小明沒有通過考試"] },
      { id: "passed", alt: "小明通過了考試", semanticSegments: ["小明通過了考試"] },
      { id: "gaveUp", alt: "小明主動放棄了實習", semanticSegments: ["小明主動放棄了實習"] },
      { id: "uncertain", alt: "無法得知是否通過考試", semanticSegments: ["無法得知是否通過考試"] }
    ],
    correctOptionId: "failed",
    distractorRationale: "通過了考試直接矛盾；主動放棄為外部臆測；無法得知忽略假言連鎖之嚴格逆否性。",
    measurementTarget: "兩步假言命題連鎖否定後件推理。",
    internalExplanation: "不能實習推出沒有獲得證書；沒有證書推出沒有通過考試。連鎖逆否完全確定。",
    suggestedTimeSeconds: 16,
    provisionalA: 1.3,
    provisionalB: 1.5,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q48", category: "logic", difficulty: "medium",
    stem: "四位學生入選條件如下：1. 若選 A，則必選 B2. 若選 C，則不能選 B3. C 與 D 必須至少選一人現在已知「確定選 A」。由此可知誰也必然入選？",
    semanticSegments: ["四位學生入選條件如下：", "1. 若選 A，則必選 B", "2. 若選 C，則不能選 B", "3. C 與 D 必須至少選一人", "現在已知「確定選 A」。", "由此可知誰也必然入選？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "d", alt: "D 必然入選", semanticSegments: ["D 必然入選"] },
      { id: "c", alt: "C 必然入選", semanticSegments: ["C 必然入選"] },
      { id: "neither", alt: "都不入選", semanticSegments: ["都不入選"] },
      { id: "uncertain", alt: "無法確定", semanticSegments: ["無法確定"] }
    ],
    correctOptionId: "d",
    distractorRationale: "C 入選會使 B 不能入選而與 A 矛盾；都不入選忽略 D 必須補位；無法確定忽略了確定推導鏈。",
    measurementTarget: "多重條件假言逆否與析取排除演繹推理。",
    internalExplanation: "選 A 推出必選 B；由「選 C 則不能選 B」逆否推出「選 B 則不能選 C」，故 C 絕不入選；又由「C 與 D 至少選一人」且 C 不入選，得出 D 必然入選。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.35,
    provisionalB: 1.55,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q49", category: "spatial", difficulty: "hard",
    stem: "紙張依箭頭摺兩次後打孔。完全攤開時，孔洞分布是哪個？",
    semanticSegments: ["紙張依箭頭", "摺兩次後打孔。", "完全攤開時，", "孔洞分布是哪個？"],
    stimulus: {"kind": "visual", "visualKey": "paper-fold-hard"},
    options: [
      { id: "four", alt: "四個孔左右與上下對稱分布", visualKey: "paper-fold-four" },
      { id: "two", alt: "兩個孔沿對角線分布", visualKey: "paper-fold-two" },
      { id: "eight", alt: "八個孔呈上下左右對稱分布", visualKey: "paper-fold-eight" },
      { id: "fourDiagonal", alt: "四個孔沿兩條對角線分布", visualKey: "paper-fold-four-diagonal" }
    ],
    correctOptionId: "four",
    distractorRationale: "兩孔只展開一次漏掉第二條摺線；八孔過度展開；對角線孔使用了錯誤斜向鏡射軸。",
    measurementTarget: "兩次正交對摺後之雙軸鏡像對稱展開推理。",
    internalExplanation: "正方形先右向左摺、再上向下摺，摺後為 1/4 面積之四層紙。打一孔展開後，沿水平軸與垂直軸各鏡射一次，形成 4 個對稱孔洞。",
    suggestedTimeSeconds: 24,
    provisionalA: 1.65,
    provisionalB: 1.6,
    provisionalC: 0.25,
    accessibilityAlt: "正方形先右向左對摺，再上向下對摺，於摺後小方形偏內處打孔。",
  },
  {
    id: "q50", category: "abstract", difficulty: "hard",
    stem: "箭頭方向與圓點數量各自變化。下一格是？",
    semanticSegments: ["箭頭方向與圓點數量", "各自變化。", "下一格是？"],
    stimulus: {"kind": "visual", "visualKey": "arrow-dots-hard"},
    options: [
      { id: "right3", alt: "向右箭頭，下方三個圓點", visualKey: "arrow-right-three" },
      { id: "down3", alt: "向下箭頭，下方三個圓點", visualKey: "arrow-down-three" },
      { id: "right2", alt: "向右箭頭，下方兩個圓點", visualKey: "arrow-right-two" },
      { id: "up3", alt: "向上箭頭，下方三個圓點", visualKey: "arrow-up-three" }
    ],
    correctOptionId: "right3",
    distractorRationale: "向下箭頭方向未維持旋轉；右二圓點數量未推進；上三箭頭方向跳位。",
    measurementTarget: "方向旋轉週期與數量步長之多重規則同步追蹤。",
    internalExplanation: "箭頭依上、右、下、左、上順時針旋轉 90 度，下一格為向右；圓點數每兩格加一（1,1, 2,2, 3），故為三個圓點。",
    suggestedTimeSeconds: 22,
    provisionalA: 1.65,
    provisionalB: 1.65,
    provisionalC: 0.25,
    accessibilityAlt: "五格序列，箭頭依上、右、下、左循環，圓點數為一、一、二、二、三。",
  },
  {
    id: "q51", category: "verbal", difficulty: "hard",
    stem: "修正之於錯誤，最接近下列哪個關係？",
    semanticSegments: ["修正之於錯誤，", "最接近下列哪個關係？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "calibrate", alt: "校準之於偏差", semanticSegments: ["校準之於偏差"] },
      { id: "measure", alt: "測量之於工具", semanticSegments: ["測量之於工具"] },
      { id: "predict", alt: "預測之於趨勢", semanticSegments: ["預測之於趨勢"] },
      { id: "compare", alt: "比較之於差異", semanticSegments: ["比較之於差異"] }
    ],
    correctOptionId: "calibrate",
    distractorRationale: "測量使用工具為手段關係；預測順應趨勢並非消除趨勢；比較辨識差異但未消除差異。",
    measurementTarget: "主動操作以消除/校正非理想偏離狀態之高階概念類比。",
    internalExplanation: "修正之目的是消除或減少錯誤；校準之目的是消除或減少測量偏差，兩者同具校正操作之本質結構。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.65,
    provisionalB: 1.7,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q52", category: "logic", difficulty: "hard",
    stem: "根據三個條件，哪個敘述必然成立？",
    semanticSegments: ["根據三個條件，", "哪個敘述必然成立？"],
    stimulus: {"kind": "logic", "lines": [["A、B、C 恰有兩個開啟"], ["C 已經開啟"], ["A、B 不會同時開啟"]]},
    options: [
      { id: "split", alt: "A、B 一開一關", semanticSegments: ["A、B 一開一關"] },
      { id: "off", alt: "A、B 都未開啟", semanticSegments: ["A、B 都未開啟"] },
      { id: "bothOn", alt: "A、B 都開啟", semanticSegments: ["A、B 都開啟"] },
      { id: "aOn", alt: "A 必開、B 必關", semanticSegments: ["A 必開、B 必關"] }
    ],
    correctOptionId: "split",
    distractorRationale: "都未開啟則總開啟數僅為 1；都開啟違反總數 2 且違反互斥；指定 A 開超過已知條件所能決定之範疇。",
    measurementTarget: "基數約束與排他相容之布林約束推理。",
    internalExplanation: "C 已開啟占去 1 個名額，A 與 B 必須再提供恰好 1 個開啟；條件又保證 A、B 不同時開，因此 A、B 必然恰為一開一關。",
    suggestedTimeSeconds: 22,
    provisionalA: 1.65,
    provisionalB: 1.75,
    provisionalC: 0.25,
    accessibilityAlt: "三行開關條件，A、B、C 為中性代號。",
  },
  {
    id: "q53", category: "workingMemory", difficulty: "hard",
    stem: "數字由小到大、字母依字母順序排列，再把數字放前面。結果是？",
    semanticSegments: ["數字由小到大、", "字母依字母順序排列，", "再把數字放前面。", "結果是？"],
    stimulus: {"kind": "memory", "values": ["E", "9", "A", "2", "C", "6"], "durationMs": 12500},
    options: [
      { id: "correct", alt: "2 6 9 ｜ A C E", semanticSegments: ["2 6 9 ｜ A C E"] },
      { id: "letters", alt: "2 6 9 ｜ E C A", semanticSegments: ["2 6 9 ｜ E C A"] },
      { id: "numberWrong", alt: "9 6 2 ｜ A C E", semanticSegments: ["9 6 2 ｜ A C E"] },
      { id: "groupWrong", alt: "A C E ｜ 2 6 9", semanticSegments: ["A C E ｜ 2 6 9"] }
    ],
    correctOptionId: "correct",
    distractorRationale: "字母未排序保留原順序；數字方向相反成降冪；分組未將數字放前面。",
    measurementTarget: "六項異質元素雙排序、分類與重組心智操作。",
    internalExplanation: "數字為 9, 2, 6 升冪排為 2, 6, 9；字母為 E, A, C 字母序排為 A, C, E；數字置前合併為 2 6 9 ｜ A C E。",
    suggestedTimeSeconds: 25,
    provisionalA: 1.7,
    provisionalB: 1.8,
    provisionalC: 0.25,
    accessibilityAlt: "先短暫顯示 E、9、A、2、C、6，接著隱藏。",
  },
  {
    id: "q54", category: "quantitative", difficulty: "hard",
    stem: "相鄰差值每次加倍。下一個數字是？",
    semanticSegments: ["相鄰差值每次加倍。", "下一個數字是？"],
    stimulus: {"kind": "sequence", "values": ["4", "7", "13", "25", "49", "？"]},
    options: [
      { id: "ninetySeven", alt: "97", semanticSegments: ["97"] },
      { id: "ninetySix", alt: "96", semanticSegments: ["96"] },
      { id: "oneHundred", alt: "100", semanticSegments: ["100"] },
      { id: "seventyThree", alt: "73", semanticSegments: ["73"] }
    ],
    correctOptionId: "ninetySeven",
    distractorRationale: "96 忽略首項基準累積；100 誤作末項乘二加二；73 沿用前一步差值 24。",
    measurementTarget: "二階差值幾何倍增（等比一階差）數列推理。",
    internalExplanation: "相鄰差值依序為 3, 6, 12, 24；下一步差值為 24 × 2 = 48。故 49 + 48 = 97。",
    suggestedTimeSeconds: 20,
    provisionalA: 1.7,
    provisionalB: 1.85,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 4、7、13、25、49、問號。",
  },
  {
    id: "q55", category: "processingSpeed", difficulty: "hard",
    stem: "兩列代碼中，第一個不同字元位於第幾個？",
    semanticSegments: ["兩列代碼中，", "第一個不同字元", "位於第幾個？"],
    stimulus: {"kind": "textRows", "rows": ["7K3M8R2Q5N", "7K3M8R2G5N"]},
    options: [
      { id: "eighth", alt: "第 8 個", semanticSegments: ["第 8 個"] },
      { id: "seventh", alt: "第 7 個", semanticSegments: ["第 7 個"] },
      { id: "sixth", alt: "第 6 個", semanticSegments: ["第 6 個"] },
      { id: "ninth", alt: "第 9 個", semanticSegments: ["第 9 個"] }
    ],
    correctOptionId: "eighth",
    distractorRationale: "第 7 與第 9 格為相鄰干擾位；第 6 格提早比對。",
    measurementTarget: "長無意義字母數字字串逐位快速比對與位置錨定。",
    internalExplanation: "逐位檢驗：1:7, 2:K, 3:3, 4:M, 5:8, 6:R, 7:2 均相同；第 8 位上方為 Q、下方為 G，首度出現相異。",
    suggestedTimeSeconds: 10,
    provisionalA: 1.7,
    provisionalB: 1.9,
    provisionalC: 0.25,
    accessibilityAlt: "兩列十字元代碼，僅有一個位置不同。",
  },
  {
    id: "q56", category: "abstract", difficulty: "hard",
    stem: "第三格只保留前兩格中沒有重複的線。缺少哪一格？",
    semanticSegments: ["第三格只保留", "前兩格中", "沒有重複的線。", "缺少哪一格？"],
    stimulus: {"kind": "visual", "visualKey": "matrix-xor-hard"},
    options: [
      { id: "xor", alt: "保留橫線與由左上到右下的斜線", visualKey: "xor-correct" },
      { id: "union", alt: "保留全部四條線", visualKey: "xor-wrong" },
      { id: "verticalSlash", alt: "保留直線與由左上到右下的斜線", visualKey: "xor-vertical-slash" },
      { id: "horizontalBack", alt: "保留橫線與由左下到右上的斜線", visualKey: "xor-horizontal-back" }
    ],
    correctOptionId: "xor",
    distractorRationale: "全部四條線誤作聯集；直線未消去；選錯斜線方向。",
    measurementTarget: "圖形線條集合對稱差（XOR 互斥消去）運算。",
    internalExplanation: "第二列第一格包含橫線、直線、左上斜線；第二格包含直線、右上斜線。直線重複故消去，保留橫線與左上斜線。",
    suggestedTimeSeconds: 25,
    provisionalA: 1.75,
    provisionalB: 1.95,
    provisionalC: 0.25,
    accessibilityAlt: "矩陣第三格採前兩格線條的對稱差，最後一格缺少。",
  },
  {
    id: "q57", category: "spatial", difficulty: "hard",
    stem: "圖形先順時針旋轉 90°，再上下翻面。哪個結果正確？",
    semanticSegments: ["圖形先", "順時針旋轉 90°，", "再上下翻面。", "哪個結果正確？"],
    stimulus: {"kind": "visual", "visualKey": "transform-two-step"},
    options: [
      { id: "correct", alt: "轉動再上下翻面後的圖形，圓點在右下", visualKey: "transform-two-correct" },
      { id: "wrong", alt: "只完成旋轉的圖形，圓點在右上", visualKey: "transform-two-wrong" },
      { id: "flipOnly", alt: "只上下翻面後的圖形，圓點在左下", visualKey: "transform-two-flip" },
      { id: "reverseOrder", alt: "先翻面再旋轉後的圖形，圓點在左上", visualKey: "transform-two-reverse" }
    ],
    correctOptionId: "correct",
    distractorRationale: "只旋轉漏做翻面；只翻面漏做旋轉；顛倒非對稱非交換性之操作次序。",
    measurementTarget: "空間剛體旋轉與軸向反射的複合非對稱轉換。",
    internalExplanation: "原圖圓點在左上。順時針 90 度後移至右上；接著上下翻面（Y軸反轉），右上點翻至右下。",
    suggestedTimeSeconds: 24,
    provisionalA: 1.75,
    provisionalB: 2.0,
    provisionalC: 0.25,
    accessibilityAlt: "不對稱折線與圓點，依序執行順時針九十度與上下翻面。",
  },
  {
    id: "q58", category: "verbal", difficulty: "hard",
    stem: "證據支持主張，最接近下列哪個關係？",
    semanticSegments: ["證據支持主張，", "最接近下列哪個關係？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "foundation", alt: "地基支撐建築", semanticSegments: ["地基支撐建築"] },
      { id: "engine", alt: "引擎推動車輛", semanticSegments: ["引擎推動車輛"] },
      { id: "map", alt: "地圖指引旅程", semanticSegments: ["地圖指引旅程"] },
      { id: "roof", alt: "屋頂覆蓋房屋", semanticSegments: ["屋頂覆蓋房屋"] }
    ],
    correctOptionId: "foundation",
    distractorRationale: "引擎提供驅動力而非基礎存在前提；地圖提供導引；屋頂提供保護覆蓋，皆非立論基石關係。",
    measurementTarget: "深層認識論基礎與實體結構支撐的抽象對稱關係。",
    internalExplanation: "證據是主張能夠立足的根本基礎，地基是建築能夠立足的根本基礎，兩者同具「底層支撐整體成立」的同構關係。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.7,
    provisionalB: 2.05,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q59", category: "logic", difficulty: "hard",
    stem: "根據四個條件，哪個結論必然成立？",
    semanticSegments: ["根據四個條件，", "哪個結論必然成立？"],
    stimulus: {"kind": "logic", "lines": [["P、Q、R 恰有兩個為真"], ["如果 Q 為真，R 就為假"], ["如果 R 為真，P 就為真"], ["P、Q 不會同時為假"]]},
    options: [
      { id: "p", alt: "P 必然為真", semanticSegments: ["P 必然為真"] },
      { id: "r", alt: "R 必然為真", semanticSegments: ["R 必然為真"] },
      { id: "q", alt: "Q 必然為真", semanticSegments: ["Q 必然為真"] },
      { id: "two", alt: "P、R 必然同真", semanticSegments: ["P、R 必然同真"] }
    ],
    correctOptionId: "p",
    distractorRationale: "R 在 Q 真時為假；Q 在 R 真時為假；P 與 R 可不同真（Q真時 R假但 P真）。",
    measurementTarget: "多命題約束系統之完全窮舉與必然真值鎖定。",
    internalExplanation: "恰有兩真：若 Q 真，則 R 假，為湊兩真必有 P 真（符合P真R假）；若 Q 假，由不得同假知 P 必真，又需兩真故 R 亦真。兩種可能情況中 P 必然皆為真。",
    suggestedTimeSeconds: 26,
    provisionalA: 1.8,
    provisionalB: 2.1,
    provisionalC: 0.25,
    accessibilityAlt: "四行命題條件，P、Q、R 為中性命題代號。",
  },
  {
    id: "q60", category: "abstract", difficulty: "hard",
    stem: "外框與圓點位置各有規則。右下角應該是哪一格？",
    semanticSegments: ["外框與圓點位置", "各有規則。", "右下角應該是哪一格？"],
    stimulus: {"kind": "visual", "visualKey": "polygon-matrix-hard"},
    options: [
      { id: "seven", alt: "七邊形，圓點位於左上角", visualKey: "polygon-seven-dot-tl" },
      { id: "six", alt: "六邊形，圓點位於左上角", visualKey: "polygon-six-dot-tl" },
      { id: "sevenBR", alt: "七邊形，圓點位於右下角", visualKey: "polygon-seven-dot-br" },
      { id: "eightTL", alt: "八邊形，圓點位於左上角", visualKey: "polygon-eight-dot-tl" }
    ],
    correctOptionId: "seven",
    distractorRationale: "六邊形邊數停滯；右下角圓點循環錯誤；八邊形邊數過度增加。",
    measurementTarget: "幾何邊數橫向等差與頂點標記循環雙重規則融合。",
    internalExplanation: "外框邊數第一列為 3, 4, 5；第二列為 5, 6，下一格為 7 邊形。圓點位置循環 0, 1, 2, 2, 3, 0，故右下角回到左上角 0。",
    suggestedTimeSeconds: 27,
    provisionalA: 1.85,
    provisionalB: 2.15,
    provisionalC: 0.25,
    accessibilityAlt: "二乘三圖形矩陣同時改變多邊形邊數與圓點位置，右下缺格。",
  },
  {
    id: "q61", category: "quantitative", difficulty: "hard",
    stem: "相鄰兩項相加得到後一項。數列問號處是？",
    semanticSegments: ["相鄰兩項相加得到後一項。", "數列問號處是？"],
    stimulus: {"kind": "sequence", "values": ["3", "4", "7", "11", "18", "29", "？"]},
    options: [
      { id: "fortySeven", alt: "47", semanticSegments: ["47"] },
      { id: "fortySix", alt: "46", semanticSegments: ["46"] },
      { id: "fortyEight", alt: "48", semanticSegments: ["48"] },
      { id: "fortyFive", alt: "45", semanticSegments: ["45"] }
    ],
    correctOptionId: "fortySeven",
    distractorRationale: "46 計算漏 1；48 加錯；45 誤採倍差。",
    measurementTarget: "費氏數列型遞迴相加規律。",
    internalExplanation: "每項均為前兩項之和：3+4=7, 4+7=11, 7+11=18, 11+18=29，故 18 + 29 = 47。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.7,
    provisionalB: 2.2,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 3、4、7、11、18、29、問號。",
  },
  {
    id: "q62", category: "workingMemory", difficulty: "hard",
    stem: "取出所有「奇數」，由大到小排列。第一個數字是？",
    semanticSegments: ["取出所有「奇數」，", "由大到小排列。", "第一個數字是？"],
    stimulus: {"kind": "memory", "values": ["7", "B", "4", "K", "2", "M", "9"], "durationMs": 13000},
    options: [
      { id: "nine", alt: "9", semanticSegments: ["9"] },
      { id: "seven", alt: "7", semanticSegments: ["7"] },
      { id: "four", alt: "4", semanticSegments: ["4"] },
      { id: "b", alt: "B", semanticSegments: ["B"] }
    ],
    correctOptionId: "nine",
    distractorRationale: "7 是較小奇數（若升冪則排第一）；4 為偶數；B 為字母干擾。",
    measurementTarget: "七項混合序列屬性過濾、降冪排序與極值萃取。",
    internalExplanation: "序列中奇數為 7、9；由大到小排列為 9、7，首項為 9。",
    suggestedTimeSeconds: 20,
    provisionalA: 1.75,
    provisionalB: 2.25,
    provisionalC: 0.25,
    accessibilityAlt: "先短暫顯示 7、B、4、K、2、M、9，接著隱藏。",
  },
  {
    id: "q63", category: "spatial", difficulty: "hard",
    stem: "立方體六面標有 1 至 6，相對面之點數和皆為 7。若 1 點朝上、2 點朝前，右側面為幾點？",
    semanticSegments: ["立方體六面標有 1 至 6，", "相對面之點數和皆為 7。", "若 1 點朝上、2 點朝前，", "右側面為幾點？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "four", alt: "4 點", semanticSegments: ["4 點"] },
      { id: "three", alt: "3 點", semanticSegments: ["3 點"] },
      { id: "five", alt: "5 點", semanticSegments: ["5 點"] },
      { id: "six", alt: "6 點", semanticSegments: ["6 點"] }
    ],
    correctOptionId: "four",
    distractorRationale: "5 點在背面（2的對面）；6 點在底面（1的對面）；3 點在左側面（標準骰子 1-2-3 逆時針或 1-2-4 順時針手性）。",
    measurementTarget: "三維立方體相對面不變性與空間三軸視角轉換。",
    internalExplanation: "相對面和為 7：1 的對面是 6（底面），2 的對面是 5（背面）。依標準右手系骰子拓撲，當 1 點在上、2 點在正面時，右側面必為 4 點（左側為 3 點）。",
    suggestedTimeSeconds: 22,
    provisionalA: 1.8,
    provisionalB: 2.3,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q64", category: "logic", difficulty: "hard",
    stem: "甲、乙、丙三人中恰有一人說真話：甲說：「乙在說謊。」乙說：「丙在說謊。」丙說：「甲和乙都在說謊。」誰在說真話？",
    semanticSegments: ["甲、乙、丙三人中恰有一人說真話：", "甲說：「乙在說謊。」", "乙說：「丙在說謊。」", "丙說：「甲和乙都在說謊。」", "誰在說真話？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "b", alt: "乙", semanticSegments: ["乙"] },
      { id: "a", alt: "甲", semanticSegments: ["甲"] },
      { id: "c", alt: "丙", semanticSegments: ["丙"] },
      { id: "none", alt: "沒有人說真話", semanticSegments: ["沒有人說真話"] }
    ],
    correctOptionId: "b",
    distractorRationale: "若甲真則乙假，乙假推出丙真，導致甲丙皆真（矛盾）；若丙真推出甲假且乙假，但乙假又推出丙真導致套疊自指矛盾。",
    measurementTarget: "真話騎士與謊話說者自指命題消解。",
    internalExplanation: "若丙真，則甲乙皆謊；但乙謊表示丙不謊，甲謊（乙說謊為偽）表示乙說真話，自相矛盾。故丙必為謊。丙謊則甲乙不皆謊，恰一真話故甲乙中恰一真。若乙真，則丙謊（符合事實），甲說「乙謊」為偽（甲確為謊），無任何矛盾。故唯一說真話者為乙。",
    suggestedTimeSeconds: 26,
    provisionalA: 1.85,
    provisionalB: 2.35,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q65", category: "abstract", difficulty: "hard",
    stem: "三乘三矩陣中：每列形狀相同，同心層數依序為 1、2、3。第三列缺格應為？",
    semanticSegments: ["三乘三矩陣中：", "每列形狀相同，", "同心層數依序為 1、2、3。", "第三列缺格應為？"],
    stimulus: {"kind": "visual", "visualKey": "matrix-triple-concentric"},
    options: [
      { id: "c3Tri", alt: "3 個同心三角形", semanticSegments: ["3 個同心三角形"] },
      { id: "c2Tri", alt: "2 個同心三角形", semanticSegments: ["2 個同心三角形"] },
      { id: "c3Circle", alt: "3 個同心圓形", semanticSegments: ["3 個同心圓形"] },
      { id: "c4Tri", alt: "4 個同心三角形", semanticSegments: ["4 個同心三角形"] }
    ],
    correctOptionId: "c3Tri",
    distractorRationale: "2 個同心三角形層數未推進；3 個同心圓形未保持第三列三角形形狀；4 個同心三角形過度推進。",
    measurementTarget: "三階圖形矩陣形狀類別不變與同心層數等差推進。",
    internalExplanation: "第一列為圓形（1,2,3層）；第二列為正方形（1,2,3層）；第三列為三角形，前兩格為 1 與 2 層，故缺格必然為 3 個同心三角形。",
    suggestedTimeSeconds: 24,
    provisionalA: 1.8,
    provisionalB: 2.4,
    provisionalC: 0.25,
    accessibilityAlt: "三乘三矩陣，同心形狀層數每列遞增。",
  },
  {
    id: "q66", category: "verbal", difficulty: "hard",
    stem: "「萌芽、成長、繁盛、凋零」是植物生命週期四階段。依照相同的歷程邏輯，「起草、修改、定稿、？」問號處應填入？",
    semanticSegments: ["「萌芽、成長、繁盛、凋零」", "是植物生命週期四階段。", "依照相同的歷程邏輯，", "「起草、修改、定稿、？」", "問號處應填入？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "publish", alt: "發布", semanticSegments: ["發布"] },
      { id: "conceive", alt: "構思", semanticSegments: ["構思"] },
      { id: "destroy", alt: "銷毀", semanticSegments: ["銷毀"] },
      { id: "suspend", alt: "擱置", semanticSegments: ["擱置"] }
    ],
    correctOptionId: "publish",
    distractorRationale: "構思為起草前的起點；銷毀為異常中斷；擱置為非完成態停頓。",
    measurementTarget: "歷程階段時間向量終局性關係映射。",
    internalExplanation: "起草（初構）→ 修改（優化）→ 定稿（成熟）→ 發布（公開實行），對應生命之發芽、生長、繁茂至最終成熟亮相階段。",
    suggestedTimeSeconds: 16,
    provisionalA: 1.7,
    provisionalB: 2.45,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q67", category: "quantitative", difficulty: "hard",
    stem: "代數符號滿足三個算式：★ ＋ ★ ＝ 12★ ＋ ▲ ＝ 10▲ ＋ ● ＝ 9問 ● 的數值是？",
    semanticSegments: ["代數符號滿足三個算式：", "★ ＋ ★ ＝ 12", "★ ＋ ▲ ＝ 10", "▲ ＋ ● ＝ 9", "問 ● 的數值是？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "five", alt: "5", semanticSegments: ["5"] },
      { id: "four", alt: "4", semanticSegments: ["4"] },
      { id: "six", alt: "6", semanticSegments: ["6"] },
      { id: "seven", alt: "7", semanticSegments: ["7"] }
    ],
    correctOptionId: "five",
    distractorRationale: "4 是 ▲ 的數值；6 是 ★ 的數值；7 計算錯誤。",
    measurementTarget: "線性符號方程組逐步消元求值。",
    internalExplanation: "由第一式 2★ = 12 得 ★ = 6；代入第二式 6 + ▲ = 10 得 ▲ = 4；代入第三式 4 + ● = 9 得 ● = 5。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.75,
    provisionalB: 2.5,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q68", category: "processingSpeed", difficulty: "hard",
    stem: "方格陣列中，唯一「圓點偏左」的符號位於哪一格？",
    semanticSegments: ["方格陣列中，", "唯一「圓點偏左」的符號", "位於哪一格？"],
    stimulus: {"kind": "visual", "visualKey": "search-dot-offset"},
    options: [
      { id: "r4c5", alt: "第 4 列第 5 格", semanticSegments: ["第 4 列第 5 格"] },
      { id: "r2c2", alt: "第 2 列第 2 格", semanticSegments: ["第 2 列第 2 格"] },
      { id: "r5c3", alt: "第 5 列第 3 格", semanticSegments: ["第 5 列第 3 格"] },
      { id: "r1c6", alt: "第 1 列第 6 格", semanticSegments: ["第 1 列第 6 格"] }
    ],
    correctOptionId: "r4c5",
    distractorRationale: "其餘所有方格中之符號圓點皆置中或偏右，僅第 4 列第 5 格明顯偏左偏離基準。",
    measurementTarget: "微小位置偏移特徵之高密度視覺搜尋抗干擾能力。",
    internalExplanation: "在六乘六陣列中逐項比對圓心相對偏軸，唯有第 4 列第 5 格之圓點座標 X 偏向左側邊緣。",
    suggestedTimeSeconds: 11,
    provisionalA: 1.8,
    provisionalB: 2.55,
    provisionalC: 0.25,
    accessibilityAlt: "六乘六符號陣列，尋找唯一圓點偏左之異常項目。",
  },
  {
    id: "q69", category: "workingMemory", difficulty: "hard",
    stem: "先記住四個數字：將大於 4 的數字減 1，小於等於 4 的數字加 1。轉換後的結果是？",
    semanticSegments: ["先記住四個數字：", "將大於 4 的數字減 1，", "小於等於 4 的數字加 1。", "轉換後的結果是？"],
    stimulus: {"kind": "memory", "values": ["3", "8", "2", "5"], "durationMs": 13500},
    options: [
      { id: "res4734", alt: "4 7 3 4", semanticSegments: ["4 7 3 4"] },
      { id: "res2916", alt: "2 9 1 6", semanticSegments: ["2 9 1 6"] },
      { id: "res4936", alt: "4 9 3 6", semanticSegments: ["4 9 3 6"] },
      { id: "res2714", alt: "2 7 1 4", semanticSegments: ["2 7 1 4"] }
    ],
    correctOptionId: "res4734",
    distractorRationale: "2 9 1 6 顛倒加減規則；4 9 3 6 全部做加法；2 7 1 4 全部做減法。",
    measurementTarget: "四項記憶保持與分流條件數值映射雙重操作。",
    internalExplanation: "3 (<=4) 加 1 得 4；8 (>4) 減 1 得 7；2 (<=4) 加 1 得 3；5 (>4) 減 1 得 4。結果為 4 7 3 4。",
    suggestedTimeSeconds: 22,
    provisionalA: 1.8,
    provisionalB: 2.6,
    provisionalC: 0.25,
    accessibilityAlt: "先短暫顯示 3、8、2、5，接著隱藏。",
  },
  {
    id: "q70", category: "abstract", difficulty: "hard",
    stem: "八角形頂點上的黑點，每次順時針跳躍 2 格。第 5 次跳躍後黑點移動了多少格？",
    semanticSegments: ["八角形頂點上的黑點，", "每次順時針跳躍 2 格。", "第 5 次跳躍後", "黑點移動了多少格？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "ten", alt: "10 格（相當於起始點順時針 2 格）", semanticSegments: ["10 格（相當於起始點順時針 2 格）"] },
      { id: "eight", alt: "8 格（回到起始點）", semanticSegments: ["8 格（回到起始點）"] },
      { id: "twelve", alt: "12 格（相當於起始點順時針 4 格）", semanticSegments: ["12 格（相當於起始點順時針 4 格）"] },
      { id: "seven", alt: "7 格", semanticSegments: ["7 格"] }
    ],
    correctOptionId: "ten",
    distractorRationale: "8 格為跳 4 次；12 格為跳 6 次；7 格為奇數誤算。",
    measurementTarget: "模 8 環形軌跡步長累積與同餘位置映射。",
    internalExplanation: "每次跳 2 格，5 次累積跳躍 5 × 2 = 10 格；在 8 頂點模運算中 10 mod 8 = 2，即順時針推進 2 格。",
    suggestedTimeSeconds: 18,
    provisionalA: 1.8,
    provisionalB: 2.65,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q71", category: "quantitative", difficulty: "extreme",
    stem: "乘數與加數同步增加。下一個數字是？",
    semanticSegments: ["乘數與加數同步增加。", "下一個數字是？"],
    stimulus: {"kind": "sequence", "values": ["2", "6", "21", "88", "？"]},
    options: [
      { id: "fourFortyFive", alt: "445", semanticSegments: ["445"] },
      { id: "fourForty", alt: "440", semanticSegments: ["440"] },
      { id: "fourFortyFour", alt: "444", semanticSegments: ["444"] },
      { id: "fiveThirtyThree", alt: "533", semanticSegments: ["533"] }
    ],
    correctOptionId: "fourFortyFive",
    distractorRationale: "440 做乘五漏加五；444 只加四；533 誤把前值乘六加五。",
    measurementTarget: "變動雙步運算同步遞增遞迴數列極限推理。",
    internalExplanation: "第 1 步：2×2 + 2 = 6；第 2 步：6×3 + 3 = 21；第 3 步：21×4 + 4 = 88；下一步為 88×5 + 5 = 440 + 5 = 445。",
    suggestedTimeSeconds: 27,
    provisionalA: 1.9,
    provisionalB: 2.7,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 2、6、21、88、問號。",
  },
  {
    id: "q72", category: "spatial", difficulty: "extreme",
    stem: "依序旋轉 90°、上下翻面、再旋轉 180°。哪個結果正確？",
    semanticSegments: ["依序旋轉 90°、", "上下翻面、", "再旋轉 180°。", "哪個結果正確？"],
    stimulus: {"kind": "visual", "visualKey": "transform-three-step"},
    options: [
      { id: "rightDiagonal", alt: "最終階梯形，實心點右上、空心點左下", visualKey: "transform-three-correct" },
      { id: "leftDiagonal", alt: "最終階梯形，實心點左上、空心點右下", visualKey: "transform-three-wrong" },
      { id: "bothTop", alt: "最終階梯形，兩個標記都在上方", visualKey: "transform-three-both-top" },
      { id: "swapped", alt: "最終階梯形，空心點右上、實心點左下", visualKey: "transform-three-swapped" }
    ],
    correctOptionId: "rightDiagonal",
    distractorRationale: "實心點左上沒有正確合成第三步 180 度轉換；雙標記同在上方漏掉旋轉；交換標記顛倒了實心與空心點身份。",
    measurementTarget: "三步複合非交換性空間幾何剛體轉換雙標記追蹤。",
    internalExplanation: "原圖左下實心、右上空心。1) 順時針90°：實心到左上、空心到右下；2) 上下翻面：實心到左下、空心到右上；3) 轉180°：實心轉至右上、空心轉至左下。唯一正解為實心右上、空心左下。",
    suggestedTimeSeconds: 32,
    provisionalA: 1.95,
    provisionalB: 2.8,
    provisionalC: 0.25,
    accessibilityAlt: "階梯形帶一實心點與一空心點，依序做三次指定轉換。",
  },
  {
    id: "q73", category: "logic", difficulty: "extreme",
    stem: "根據四個條件，R 和 Q 的關係必然是？",
    semanticSegments: ["根據四個條件，", "R 和 Q 的關係", "必然是？"],
    stimulus: {"kind": "logic", "lines": [["P、Q、R、S 恰有兩個為真"], ["P、Q 恰有一個為真"], ["如果 P 為真，R 就為真"], ["S 與 Q 真值相同"]]},
    options: [
      { id: "opposite", alt: "R、Q 恰有一個為真", semanticSegments: ["R、Q 恰有一個為真"] },
      { id: "same", alt: "R、Q 真值相同", semanticSegments: ["R、Q 真值相同"] },
      { id: "bothTrue", alt: "R、Q 必然都為真", semanticSegments: ["R、Q 必然都為真"] },
      { id: "bothFalse", alt: "R、Q 必然都為假", semanticSegments: ["R、Q 必然都為假"] }
    ],
    correctOptionId: "opposite",
    distractorRationale: "真值相同與總真值數 2 衝突；都為真或都為假無法滿足 P、Q 恰一真及 S=Q。",
    measurementTarget: "高難度四元命題邏輯約束與真值互補演繹。",
    internalExplanation: "若 Q 真，則 S 真（已 2 真），又 P 假，故 R 必假（Q 真 R 假）；若 Q 假，則 P 真（因 P、Q 恰一真），由 P→R 知 R 必真（Q 假 R 真）。在所有成立情況下，R 與 Q 必然一真一假，即恰有一真。",
    suggestedTimeSeconds: 31,
    provisionalA: 2.0,
    provisionalB: 2.9,
    provisionalC: 0.25,
    accessibilityAlt: "四行命題邏輯條件，P、Q、R、S 為中性代號。",
  },
  {
    id: "q74", category: "workingMemory", difficulty: "extreme",
    stem: "數字由大到小、字母依字母順序，再從字母開始交錯排列。結果是？",
    semanticSegments: ["數字由大到小、", "字母依字母順序，", "再從字母開始", "交錯排列。", "結果是？"],
    stimulus: {"kind": "memory", "values": ["8", "D", "3", "A", "6", "F", "1", "C"], "durationMs": 15500},
    options: [
      { id: "correct", alt: "A8 C6 D3 F1", semanticSegments: ["A8 C6 D3 F1"] },
      { id: "mispaired", alt: "A8 C3 D6 F1", semanticSegments: ["A8 C3 D6 F1"] },
      { id: "lettersDown", alt: "F8 D6 C3 A1", semanticSegments: ["F8 D6 C3 A1"] },
      { id: "numbersUp", alt: "A1 C3 D6 F8", semanticSegments: ["A1 C3 D6 F8"] }
    ],
    correctOptionId: "correct",
    distractorRationale: "數字中間兩項降冪顛倒；字母反向排序；數字方向錯成升冪排列。",
    measurementTarget: "八項高負荷多維度提取、雙軌排序與交錯重組極限工作記憶操作。",
    internalExplanation: "數字降冪為 8, 6, 3, 1；字母升冪為 A, C, D, F；以字母起始交錯重組為 A8 C6 D3 F1。",
    suggestedTimeSeconds: 34,
    provisionalA: 2.0,
    provisionalB: 3.0,
    provisionalC: 0.25,
    accessibilityAlt: "先短暫顯示 8、D、3、A、6、F、1、C，接著隱藏。",
  },
  {
    id: "q75", category: "processingSpeed", difficulty: "extreme",
    stem: "目標符號共有幾個？",
    semanticSegments: ["目標符號", "共有幾個？"],
    stimulus: {"kind": "visual", "visualKey": "search-target-extreme"},
    options: [
      { id: "six", alt: "6 個", semanticSegments: ["6 個"] },
      { id: "seven", alt: "7 個", semanticSegments: ["7 個"] },
      { id: "five", alt: "5 個", semanticSegments: ["5 個"] },
      { id: "eight", alt: "8 個", semanticSegments: ["8 個"] }
    ],
    correctOptionId: "six",
    distractorRationale: "7 與 8 把缺口或圓點角度極其相似的干擾符號重複計入；5 漏看密集處。",
    measurementTarget: "高相似度多特徵結合（缺口朝上且圓點右下）抗高度干擾極限視覺搜尋速度。",
    internalExplanation: "在六乘六陣列中，同時具備「缺口朝正上（0度）」與「圓點位於右下」的目標完全相同者精確為 6 個。",
    suggestedTimeSeconds: 14,
    provisionalA: 2.05,
    provisionalB: 3.1,
    provisionalC: 0.25,
    accessibilityAlt: "六乘六符號陣列，上方示範目標；陣列中有六個相同目標。",
  },
  {
    id: "q76", category: "abstract", difficulty: "extreme",
    stem: "外框、內線與圓點各自遵循規則。右下角是哪一格？",
    semanticSegments: ["外框、內線與圓點", "各自遵循規則。", "右下角是哪一格？"],
    stimulus: {"kind": "visual", "visualKey": "matrix-triple-extreme"},
    options: [
      { id: "correct", alt: "七邊形、斜線由左下到右上、圓點在左上", visualKey: "matrix-triple-correct" },
      { id: "lineError", alt: "七邊形、斜線由左上到右下、圓點在左上", visualKey: "matrix-triple-wrong" },
      { id: "shapeError", alt: "六邊形、斜線由左下到右上、圓點在左上", visualKey: "matrix-triple-six" },
      { id: "dotError", alt: "七邊形、斜線由左下到右上、圓點在右上", visualKey: "matrix-triple-dot" }
    ],
    correctOptionId: "correct",
    distractorRationale: "內線方向循環停滯；外框邊數遞增未完成；圓點循環跳位未回到左上。",
    measurementTarget: "三階圖形矩陣三變數完全獨立規則融合推理。",
    internalExplanation: "邊數第三列為 5, 6, 7；內線方向為反斜線、橫線、正斜線；圓點位置依 2, 3, 0 循環回左上角 0。三者合成唯一正解。",
    suggestedTimeSeconds: 34,
    provisionalA: 2.1,
    provisionalB: 3.2,
    provisionalC: 0.25,
    accessibilityAlt: "三乘三矩陣同時改變多邊形邊數、內線方向與圓點位置，右下缺格。",
  },
  {
    id: "q77", category: "quantitative", difficulty: "extreme",
    stem: "觀察指數遞增數列，下一個數字是？",
    semanticSegments: ["觀察指數遞增數列，", "下一個數字是？"],
    stimulus: {"kind": "sequence", "values": ["1", "3", "7", "15", "31", "63", "127", "？"]},
    options: [
      { id: "twoFiftyFive", alt: "255", semanticSegments: ["255"] },
      { id: "twoFiftySix", alt: "256", semanticSegments: ["256"] },
      { id: "twoFiftyFour", alt: "254", semanticSegments: ["254"] },
      { id: "twoFiftySeven", alt: "257", semanticSegments: ["257"] }
    ],
    correctOptionId: "twoFiftyFive",
    distractorRationale: "256 誤算為純 2 的八次方；254 減二算錯；257 加多了一。",
    measurementTarget: "2 的 n 次方減 1（二階指數差倍增）高階數列推理。",
    internalExplanation: "各項通式為 2^k - 1 或相鄰兩項乘以 2 加 1：127 × 2 + 1 = 254 + 1 = 255（2^8 - 1 = 256 - 1 = 255）。",
    suggestedTimeSeconds: 25,
    provisionalA: 2.0,
    provisionalB: 3.3,
    provisionalC: 0.25,
    accessibilityAlt: "數列為 1、3、7、15、31、63、127、問號。",
  },
  {
    id: "q78", category: "spatial", difficulty: "extreme",
    stem: "正方形沿兩條對角線連續對摺兩次成三角形，在直角頂點處剪去一角。完全攤開後，圖形正中央會呈現什麼？",
    semanticSegments: ["正方形沿兩條對角線", "連續對摺兩次成三角形，", "在直角頂點處剪去一角。", "完全攤開後，", "圖形正中央會呈現什麼？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "centerDiamond", alt: "中央一個菱形（正方形）孔洞", semanticSegments: ["中央一個菱形（正方形）孔洞"] },
      { id: "fourHoles", alt: "四個分散的孔洞", semanticSegments: ["四個分散的孔洞"] },
      { id: "edgeNotches", alt: "四個邊緣的缺口", semanticSegments: ["四個邊緣的缺口"] },
      { id: "noHole", alt: "沒有孔洞，只有摺痕", semanticSegments: ["沒有孔洞，只有摺痕"] }
    ],
    correctOptionId: "centerDiamond",
    distractorRationale: "分散四孔誤將直角頂點當作底角外邊；邊緣缺口混淆了對摺後的頂點所對應的原始位置；無孔洞忽略剪角操作。",
    measurementTarget: "雙對角線正交摺疊與共頂點展開空間拓撲重構。",
    internalExplanation: "正方形沿兩對角線摺兩次後，所有四個原始扇區的共用幾何中心點，恰好匯聚在該三角形之直角頂點處。剪去直角頂點，攤開後四個摺角缺口在正中央閉合為一個菱形（正方形）孔洞。",
    suggestedTimeSeconds: 28,
    provisionalA: 2.05,
    provisionalB: 3.4,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q79", category: "logic", difficulty: "extreme",
    stem: "評選中五位候選人滿足條件：1. A 與 B 至少一人入選2. 若 B 入選，則 C 必須入選3. 若 C 入選，則 E 不能入選4. 現在確定「E 已經入選」由此可知誰必然入選？",
    semanticSegments: ["評選中五位候選人滿足條件：", "1. A 與 B 至少一人入選", "2. 若 B 入選，則 C 必須入選", "3. 若 C 入選，則 E 不能入選", "4. 現在確定「E 已經入選」", "由此可知誰必然入選？"],
    stimulus: {"kind": "none"},
    options: [
      { id: "a", alt: "A 必然入選", semanticSegments: ["A 必然入選"] },
      { id: "b", alt: "B 必然入選", semanticSegments: ["B 必然入選"] },
      { id: "c", alt: "C 必然入選", semanticSegments: ["C 必然入選"] },
      { id: "none", alt: "無法確定任何人入選", semanticSegments: ["無法確定任何人入選"] }
    ],
    correctOptionId: "a",
    distractorRationale: "B 入選導致 C 入選而 E 不能入選，與條件 4 矛盾；C 入選同樣排除 E；無法確定忽略必然演繹鏈。",
    measurementTarget: "多條件假言連鎖排除與析取三段論複合演繹。",
    internalExplanation: "E 確定入選：由條件 3 逆否律「E 入選 → C 不入選」得知 C 絕未入選；由條件 2 逆否律「C 不入選 → B 不入選」得知 B 絕未入選；再由條件 1「A 與 B 至少一人入選」且 B 未入選，得出 A 必然入選。邏輯鏈條嚴密無缺。",
    suggestedTimeSeconds: 30,
    provisionalA: 2.1,
    provisionalB: 3.5,
    provisionalC: 0.25,
    accessibilityAlt: "沒有額外圖形。",
  },
  {
    id: "q80", category: "abstract", difficulty: "extreme",
    stem: "三乘三拉丁方陣中，每行每列皆恰包含：形狀（圓、正方、三角）、填色（空心、條紋、實心）、圓點（上、中、下）。右下角必須是？",
    semanticSegments: ["三乘三拉丁方陣中，", "每行每列皆恰包含：", "形狀（圓、正方、三角）、", "填色（空心、條紋、實心）、", "圓點（上、中、下）。", "右下角必須是？"],
    stimulus: {"kind": "visual", "visualKey": "matrix-latin-triple"},
    options: [
      { id: "correct", alt: "實心三角形，圓點在下方", semanticSegments: ["實心三角形，圓點在下方"] },
      { id: "wrongShape", alt: "實心正方形，圓點在下方", semanticSegments: ["實心正方形，圓點在下方"] },
      { id: "wrongFill", alt: "條紋三角形，圓點在下方", semanticSegments: ["條紋三角形，圓點在下方"] },
      { id: "wrongDot", alt: "實心三角形，圓點在上方", semanticSegments: ["實心三角形，圓點在上方"] }
    ],
    correctOptionId: "correct",
    distractorRationale: "實心正方形違反第三列第三欄無重複三角形；條紋違反填色拉丁方互斥；圓點上方違反垂直欄圓點位置分佈。",
    measurementTarget: "高階三維度正交拉丁方陣（Euler's Orthogonal Latin Squares）極限多約束推理。",
    internalExplanation: "第 3 列已有圓形與正方形，缺三角形；第 3 欄已有空心與條紋，缺實心；第 3 列與第 3 欄已有圓點在上與居中，缺圓點在下方。三特徵交集唯有「實心三角形，圓點在下方」。",
    suggestedTimeSeconds: 35,
    provisionalA: 2.15,
    provisionalB: 3.65,
    provisionalC: 0.25,
    accessibilityAlt: "三乘三矩陣，行與列三維屬性拉丁方陣。",
  },
];

export const itemById = new Map(ASSESSMENT_ITEMS.map((item) => [item.id, item]));
